package mnj.mfg.model.views;

import mnj.mfg.model.entities.MarkerLayplanDetImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 23 11:14:29 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MarkerLayPlanVORowImpl extends ViewRowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MarkerLayPlanVORowImpl() {
    }

    /**
     * Gets MarkerLayplanDet entity object.
     * @return the MarkerLayplanDet
     */
    public MarkerLayplanDetImpl getMarkerLayplanDet() {
        return (MarkerLayplanDetImpl)getEntity(0);
    }
}
