package mnj.mfg.model.views;

import mnj.mfg.model.entities.MnjMfgRatioplanSizlineImpl;

import oracle.jbo.RowSet;
import oracle.jbo.RowSetIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 08 16:26:25 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgRatioplanSizlineViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DivisionId {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getDivisionId();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setDivisionId((String)value);
            }
        }
        ,
        RatioplanId {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getRatioplanId();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setRatioplanId((Number)value);
            }
        }
        ,
        RatioplanNumber {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getRatioplanNumber();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setRatioplanNumber((Number)value);
            }
        }
        ,
        PlylineId {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getPlylineId();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setPlylineId((Number)value);
            }
        }
        ,
        SizlineId {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getSizlineId();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setSizlineId((Number)value);
            }
        }
        ,
        SalesorderId {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getSalesorderId();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setSalesorderId((Number)value);
            }
        }
        ,
        SizeId {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getSizeId();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setSizeId((String)value);
            }
        }
        ,
        Remarks {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getRemarks();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        CuttingRatio {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getCuttingRatio();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setCuttingRatio((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        TotalRatio {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getTotalRatio();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setTotalRatio((Number)value);
            }
        }
        ,
        Pcs {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getPcs();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setPcs((Number)value);
            }
        }
        ,
        TotalPcs {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getTotalPcs();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setTotalPcs((Number)value);
            }
        }
        ,
        Inseam {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getInseam();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setInseam((Number)value);
            }
        }
        ,
        SizeQty {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getSizeQty();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setSizeQty((Number)value);
            }
        }
        ,
        PlanCutQty {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getPlanCutQty();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setPlanCutQty((Number)value);
            }
        }
        ,
        BalQty {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getBalQty();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setBalQty((Number)value);
            }
        }
        ,
        PlanQty {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getPlanQty();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setPlanQty((Number)value);
            }
        }
        ,
        InseamVO1 {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getInseamVO1();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        InseamVOProgramtic1 {
            public Object get(MnjMfgRatioplanSizlineViewRowImpl obj) {
                return obj.getInseamVOProgramtic1();
            }

            public void put(MnjMfgRatioplanSizlineViewRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjMfgRatioplanSizlineViewRowImpl object);

        public abstract void put(MnjMfgRatioplanSizlineViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int RATIOPLANID = AttributesEnum.RatioplanId.index();
    public static final int RATIOPLANNUMBER = AttributesEnum.RatioplanNumber.index();
    public static final int PLYLINEID = AttributesEnum.PlylineId.index();
    public static final int SIZLINEID = AttributesEnum.SizlineId.index();
    public static final int SALESORDERID = AttributesEnum.SalesorderId.index();
    public static final int SIZEID = AttributesEnum.SizeId.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int CUTTINGRATIO = AttributesEnum.CuttingRatio.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int TOTALRATIO = AttributesEnum.TotalRatio.index();
    public static final int PCS = AttributesEnum.Pcs.index();
    public static final int TOTALPCS = AttributesEnum.TotalPcs.index();
    public static final int INSEAM = AttributesEnum.Inseam.index();
    public static final int SIZEQTY = AttributesEnum.SizeQty.index();
    public static final int PLANCUTQTY = AttributesEnum.PlanCutQty.index();
    public static final int BALQTY = AttributesEnum.BalQty.index();
    public static final int PLANQTY = AttributesEnum.PlanQty.index();
    public static final int INSEAMVO1 = AttributesEnum.InseamVO1.index();
    public static final int INSEAMVOPROGRAMTIC1 = AttributesEnum.InseamVOProgramtic1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgRatioplanSizlineViewRowImpl() {
    }

    /**
     * Gets MnjMfgRatioplanSizline entity object.
     * @return the MnjMfgRatioplanSizline
     */
    public MnjMfgRatioplanSizlineImpl getMnjMfgRatioplanSizline() {
        return (MnjMfgRatioplanSizlineImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for DIVISION_ID using the alias name DivisionId.
     * @return the DIVISION_ID
     */
    public String getDivisionId() {
        return (String) getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for DIVISION_ID using the alias name DivisionId.
     * @param value value to set the DIVISION_ID
     */
    public void setDivisionId(String value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for RATIOPLAN_ID using the alias name RatioplanId.
     * @return the RATIOPLAN_ID
     */
    public Number getRatioplanId() {
        return (Number) getAttributeInternal(RATIOPLANID);
    }

    /**
     * Sets <code>value</code> as attribute value for RATIOPLAN_ID using the alias name RatioplanId.
     * @param value value to set the RATIOPLAN_ID
     */
    public void setRatioplanId(Number value) {
        setAttributeInternal(RATIOPLANID, value);
    }

    /**
     * Gets the attribute value for RATIOPLAN_NUMBER using the alias name RatioplanNumber.
     * @return the RATIOPLAN_NUMBER
     */
    public Number getRatioplanNumber() {
        return (Number) getAttributeInternal(RATIOPLANNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for RATIOPLAN_NUMBER using the alias name RatioplanNumber.
     * @param value value to set the RATIOPLAN_NUMBER
     */
    public void setRatioplanNumber(Number value) {
        setAttributeInternal(RATIOPLANNUMBER, value);
    }

    /**
     * Gets the attribute value for PLYLINE_ID using the alias name PlylineId.
     * @return the PLYLINE_ID
     */
    public Number getPlylineId() {
        return (Number) getAttributeInternal(PLYLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for PLYLINE_ID using the alias name PlylineId.
     * @param value value to set the PLYLINE_ID
     */
    public void setPlylineId(Number value) {
        setAttributeInternal(PLYLINEID, value);
    }

    /**
     * Gets the attribute value for SIZLINE_ID using the alias name SizlineId.
     * @return the SIZLINE_ID
     */
    public Number getSizlineId() {
        return (Number) getAttributeInternal(SIZLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for SIZLINE_ID using the alias name SizlineId.
     * @param value value to set the SIZLINE_ID
     */
    public void setSizlineId(Number value) {
        setAttributeInternal(SIZLINEID, value);
    }

    /**
     * Gets the attribute value for SALESORDER_ID using the alias name SalesorderId.
     * @return the SALESORDER_ID
     */
    public Number getSalesorderId() {
        return (Number) getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SALESORDER_ID using the alias name SalesorderId.
     * @param value value to set the SALESORDER_ID
     */
    public void setSalesorderId(Number value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for SIZE_ID using the alias name SizeId.
     * @return the SIZE_ID
     */
    public String getSizeId() {
        return (String) getAttributeInternal(SIZEID);
    }

    /**
     * Sets <code>value</code> as attribute value for SIZE_ID using the alias name SizeId.
     * @param value value to set the SIZE_ID
     */
    public void setSizeId(String value) {
        setAttributeInternal(SIZEID, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for CUTTING_RATIO using the alias name CuttingRatio.
     * @return the CUTTING_RATIO
     */
    public Number getCuttingRatio() {
        return (Number) getAttributeInternal(CUTTINGRATIO);
    }

    /**
     * Sets <code>value</code> as attribute value for CUTTING_RATIO using the alias name CuttingRatio.
     * @param value value to set the CUTTING_RATIO
     */
    public void setCuttingRatio(Number value) {
        setAttributeInternal(CUTTINGRATIO, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalRatio.
     * @return the TotalRatio
     */
    public Number getTotalRatio() {
       // return (Number) getAttributeInternal(TOTALRATIO);
       oracle.jbo.domain.Number total  = new  oracle.jbo.domain.Number(0);
                   oracle.jbo.domain.Number rowValue  = new  oracle.jbo.domain.Number(0);
                   RowSetIterator iter = getViewObject().createRowSetIterator("abc");
                   while (iter.hasNext()){
                       oracle.jbo.Row r = iter.next();
                       try{
                           rowValue =(oracle.jbo.domain.Number)r.getAttribute("CuttingRatio");
                           if (rowValue != null)
                           total = total.add(rowValue);
                       }catch(Exception e){
                           iter.closeRowSetIterator();
                       }
                   }//end of while loop
              
                   iter.closeRowSetIterator();
               
                   return total; 
        
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalRatio.
     * @param value value to set the  TotalRatio
     */
    public void setTotalRatio(Number value) {
        setAttributeInternal(TOTALRATIO, value);
    }

    /**
     * Gets the attribute value for PCS using the alias name Pcs.
     * @return the PCS
     */
    public Number getPcs() {
        return (Number) getAttributeInternal(PCS);
       
    }

    /**
     * Sets <code>value</code> as attribute value for PCS using the alias name Pcs.
     * @param value value to set the PCS
     */
    public void setPcs(Number value) {
        setAttributeInternal(PCS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalPcs.
     * @return the TotalPcs
     */
    public Number getTotalPcs() {
      //  return (Number) getAttributeInternal(TOTALPCS);
      oracle.jbo.domain.Number total  = new  oracle.jbo.domain.Number(0);
                  oracle.jbo.domain.Number rowValue  = new  oracle.jbo.domain.Number(0);
                  RowSetIterator iter = getViewObject().createRowSetIterator("abc");
                  while (iter.hasNext()){
                      oracle.jbo.Row r = iter.next();
                      try{
                          rowValue =(oracle.jbo.domain.Number)r.getAttribute("Pcs");
                          if (rowValue != null)
                          total = total.add(rowValue);
                      }catch(Exception e){
                          iter.closeRowSetIterator();
                      }
                  }//end of while loop
             
                  iter.closeRowSetIterator();
              
                  return total; 
       

    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalPcs.
     * @param value value to set the  TotalPcs
     */
    public void setTotalPcs(Number value) {
        setAttributeInternal(TOTALPCS, value);
    }

    /**
     * Gets the attribute value for INSEAM using the alias name Inseam.
     * @return the INSEAM
     */
    public Number getInseam() {
        return (Number) getAttributeInternal(INSEAM);
    }

    /**
     * Sets <code>value</code> as attribute value for INSEAM using the alias name Inseam.
     * @param value value to set the INSEAM
     */
    public void setInseam(Number value) {
        setAttributeInternal(INSEAM, value);
    }

    /**
     * Gets the attribute value for SIZE_QTY using the alias name SizeQty.
     * @return the SIZE_QTY
     */
    public Number getSizeQty() {
        return (Number) getAttributeInternal(SIZEQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for SIZE_QTY using the alias name SizeQty.
     * @param value value to set the SIZE_QTY
     */
    public void setSizeQty(Number value) {
        setAttributeInternal(SIZEQTY, value);
    }

    /**
     * Gets the attribute value for PLAN_CUT_QTY using the alias name PlanCutQty.
     * @return the PLAN_CUT_QTY
     */
    public Number getPlanCutQty() {
        return (Number) getAttributeInternal(PLANCUTQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for PLAN_CUT_QTY using the alias name PlanCutQty.
     * @param value value to set the PLAN_CUT_QTY
     */
    public void setPlanCutQty(Number value) {
        setAttributeInternal(PLANCUTQTY, value);
    }

    /**
     * Gets the attribute value for BAL_QTY using the alias name BalQty.
     * @return the BAL_QTY
     */
    public Number getBalQty() {
        return (Number) getAttributeInternal(BALQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for BAL_QTY using the alias name BalQty.
     * @param value value to set the BAL_QTY
     */
    public void setBalQty(Number value) {
        setAttributeInternal(BALQTY, value);
    }

    /**
     * Gets the attribute value for PLAN_QTY using the alias name PlanQty.
     * @return the PLAN_QTY
     */
    public Number getPlanQty() {
        return (Number) getAttributeInternal(PLANQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for PLAN_QTY using the alias name PlanQty.
     * @param value value to set the PLAN_QTY
     */
    public void setPlanQty(Number value) {
        setAttributeInternal(PLANQTY, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> InseamVO1.
     */
    public RowSet getInseamVO1() {
        return (RowSet)getAttributeInternal(INSEAMVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> InseamVOProgramtic1.
     */
    public RowSet getInseamVOProgramtic1() {
        return (RowSet)getAttributeInternal(INSEAMVOPROGRAMTIC1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
