package mnj.mfg.model.views;

import mnj.mfg.model.entities.MnjMfgRatioplanPlylineImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.RowSetIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 08 17:21:28 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgRatioplanPlylineViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DivisionId {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getDivisionId();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setDivisionId((String)value);
            }
        }
        ,
        RatioplanId {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getRatioplanId();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setRatioplanId((Number)value);
            }
        }
        ,
        RatioplanNumber {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getRatioplanNumber();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setRatioplanNumber((Number)value);
            }
        }
        ,
        PlylineId {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getPlylineId();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setPlylineId((Number)value);
            }
        }
        ,
        Ply {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getPly();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setPly((Number)value);
            }
        }
        ,
        Totalpcs {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getTotalpcs();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setTotalpcs((Number)value);
            }
        }
        ,
        CuttingRatio {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getCuttingRatio();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setCuttingRatio((String)value);
            }
        }
        ,
        SizeRatio {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getSizeRatio();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setSizeRatio((String)value);
            }
        }
        ,
        TotalRatios {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getTotalRatios();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setTotalRatios((Number)value);
            }
        }
        ,
        Markerread {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getMarkerread();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setMarkerread((String)value);
            }
        }
        ,
        Markerpost {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getMarkerpost();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setMarkerpost((String)value);
            }
        }
        ,
        RpForId {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getRpForId();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setRpForId((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        TotalPieces {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getTotalPieces();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setTotalPieces((Number)value);
            }
        }
        ,
        ToTalLays {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getToTalLays();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setToTalLays((Number)value);
            }
        }
        ,
        CutNo {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getCutNo();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setCutNo((String)value);
            }
        }
        ,
        CutSrNo {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getCutSrNo();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setCutSrNo((Number)value);
            }
        }
        ,
        ShipPriority {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getShipPriority();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setShipPriority((String)value);
            }
        }
        ,
        Pattern {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getPattern();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setPattern((String)value);
            }
        }
        ,
        InseamPattern {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getInseamPattern();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setInseamPattern((String)value);
            }
        }
        ,
        TotalInseamQty {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getTotalInseamQty();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setTotalInseamQty((Number)value);
            }
        }
        ,
        BlncInseamQty {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getBlncInseamQty();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setBlncInseamQty((Number)value);
            }
        }
        ,
        MnjMfgRatioplanPlycflineView {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getMnjMfgRatioplanPlycflineView();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjMfgRatioplanSizlineView {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getMnjMfgRatioplanSizlineView();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MarkerLayPlanVO {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getMarkerLayPlanVO();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BundleDetailVO {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getBundleDetailVO();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ShipPriorityVO1 {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getShipPriorityVO1();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        InseamSizeQualityPlanVO1 {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getInseamSizeQualityPlanVO1();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        NewInseamLOV1 {
            public Object get(MnjMfgRatioplanPlylineViewRowImpl obj) {
                return obj.getNewInseamLOV1();
            }

            public void put(MnjMfgRatioplanPlylineViewRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjMfgRatioplanPlylineViewRowImpl object);

        public abstract void put(MnjMfgRatioplanPlylineViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int RATIOPLANID = AttributesEnum.RatioplanId.index();
    public static final int RATIOPLANNUMBER = AttributesEnum.RatioplanNumber.index();
    public static final int PLYLINEID = AttributesEnum.PlylineId.index();
    public static final int PLY = AttributesEnum.Ply.index();
    public static final int TOTALPCS = AttributesEnum.Totalpcs.index();
    public static final int CUTTINGRATIO = AttributesEnum.CuttingRatio.index();
    public static final int SIZERATIO = AttributesEnum.SizeRatio.index();
    public static final int TOTALRATIOS = AttributesEnum.TotalRatios.index();
    public static final int MARKERREAD = AttributesEnum.Markerread.index();
    public static final int MARKERPOST = AttributesEnum.Markerpost.index();
    public static final int RPFORID = AttributesEnum.RpForId.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int TOTALPIECES = AttributesEnum.TotalPieces.index();
    public static final int TOTALLAYS = AttributesEnum.ToTalLays.index();
    public static final int CUTNO = AttributesEnum.CutNo.index();
    public static final int CUTSRNO = AttributesEnum.CutSrNo.index();
    public static final int SHIPPRIORITY = AttributesEnum.ShipPriority.index();
    public static final int PATTERN = AttributesEnum.Pattern.index();
    public static final int INSEAMPATTERN = AttributesEnum.InseamPattern.index();
    public static final int TOTALINSEAMQTY = AttributesEnum.TotalInseamQty.index();
    public static final int BLNCINSEAMQTY = AttributesEnum.BlncInseamQty.index();
    public static final int MNJMFGRATIOPLANPLYCFLINEVIEW = AttributesEnum.MnjMfgRatioplanPlycflineView.index();
    public static final int MNJMFGRATIOPLANSIZLINEVIEW = AttributesEnum.MnjMfgRatioplanSizlineView.index();
    public static final int MARKERLAYPLANVO = AttributesEnum.MarkerLayPlanVO.index();
    public static final int BUNDLEDETAILVO = AttributesEnum.BundleDetailVO.index();
    public static final int SHIPPRIORITYVO1 = AttributesEnum.ShipPriorityVO1.index();
    public static final int INSEAMSIZEQUALITYPLANVO1 = AttributesEnum.InseamSizeQualityPlanVO1.index();
    public static final int NEWINSEAMLOV1 = AttributesEnum.NewInseamLOV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgRatioplanPlylineViewRowImpl() {
    }

    /**
     * Gets MnjMfgRatioplanPlyline entity object.
     * @return the MnjMfgRatioplanPlyline
     */
    public MnjMfgRatioplanPlylineImpl getMnjMfgRatioplanPlyline() {
        return (MnjMfgRatioplanPlylineImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for DIVISION_ID using the alias name DivisionId.
     * @return the DIVISION_ID
     */
    public String getDivisionId() {
        return (String)getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for DIVISION_ID using the alias name DivisionId.
     * @param value value to set the DIVISION_ID
     */
    public void setDivisionId(String value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for RATIOPLAN_ID using the alias name RatioplanId.
     * @return the RATIOPLAN_ID
     */
    public Number getRatioplanId() {
        return (Number)getAttributeInternal(RATIOPLANID);
    }

    /**
     * Sets <code>value</code> as attribute value for RATIOPLAN_ID using the alias name RatioplanId.
     * @param value value to set the RATIOPLAN_ID
     */
    public void setRatioplanId(Number value) {
        setAttributeInternal(RATIOPLANID, value);
    }

    /**
     * Gets the attribute value for RATIOPLAN_NUMBER using the alias name RatioplanNumber.
     * @return the RATIOPLAN_NUMBER
     */
    public Number getRatioplanNumber() {
        return (Number)getAttributeInternal(RATIOPLANNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for RATIOPLAN_NUMBER using the alias name RatioplanNumber.
     * @param value value to set the RATIOPLAN_NUMBER
     */
    public void setRatioplanNumber(Number value) {
        setAttributeInternal(RATIOPLANNUMBER, value);
    }

    /**
     * Gets the attribute value for PLYLINE_ID using the alias name PlylineId.
     * @return the PLYLINE_ID
     */
    public Number getPlylineId() {
        return (Number)getAttributeInternal(PLYLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for PLYLINE_ID using the alias name PlylineId.
     * @param value value to set the PLYLINE_ID
     */
    public void setPlylineId(Number value) {
        setAttributeInternal(PLYLINEID, value);
    }

    /**
     * Gets the attribute value for PLY using the alias name Ply.
     * @return the PLY
     */
    public Number getPly() {
        return (Number)getAttributeInternal(PLY);
    }

    /**
     * Sets <code>value</code> as attribute value for PLY using the alias name Ply.
     * @param value value to set the PLY
     */
    public void setPly(Number value) {
        setAttributeInternal(PLY, value);
    }

    /**
     * Gets the attribute value for TOTALPCS using the alias name Totalpcs.
     * @return the TOTALPCS
     */
    public Number getTotalpcs() {
        return (Number)getAttributeInternal(TOTALPCS);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTALPCS using the alias name Totalpcs.
     * @param value value to set the TOTALPCS
     */
    public void setTotalpcs(Number value) {
        setAttributeInternal(TOTALPCS, value);
    }

    /**
     * Gets the attribute value for CUTTING_RATIO using the alias name CuttingRatio.
     * @return the CUTTING_RATIO
     */
    public String getCuttingRatio() {
        return (String)getAttributeInternal(CUTTINGRATIO);
    }

    /**
     * Sets <code>value</code> as attribute value for CUTTING_RATIO using the alias name CuttingRatio.
     * @param value value to set the CUTTING_RATIO
     */
    public void setCuttingRatio(String value) {
        setAttributeInternal(CUTTINGRATIO, value);
    }

    /**
     * Gets the attribute value for SIZE_RATIO using the alias name SizeRatio.
     * @return the SIZE_RATIO
     */
    public String getSizeRatio() {
        return (String)getAttributeInternal(SIZERATIO);
    }

    /**
     * Sets <code>value</code> as attribute value for SIZE_RATIO using the alias name SizeRatio.
     * @param value value to set the SIZE_RATIO
     */
    public void setSizeRatio(String value) {
        setAttributeInternal(SIZERATIO, value);
    }

    /**
     * Gets the attribute value for TOTAL_RATIOS using the alias name TotalRatios.
     * @return the TOTAL_RATIOS
     */
    public Number getTotalRatios() {
        return (Number)getAttributeInternal(TOTALRATIOS);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_RATIOS using the alias name TotalRatios.
     * @param value value to set the TOTAL_RATIOS
     */
    public void setTotalRatios(Number value) {
        setAttributeInternal(TOTALRATIOS, value);
    }

    /**
     * Gets the attribute value for MARKERREAD using the alias name Markerread.
     * @return the MARKERREAD
     */
    public String getMarkerread() {
        return (String)getAttributeInternal(MARKERREAD);
    }

    /**
     * Sets <code>value</code> as attribute value for MARKERREAD using the alias name Markerread.
     * @param value value to set the MARKERREAD
     */
    public void setMarkerread(String value) {
        setAttributeInternal(MARKERREAD, value);
    }

    /**
     * Gets the attribute value for MARKERPOST using the alias name Markerpost.
     * @return the MARKERPOST
     */
    public String getMarkerpost() {
        return (String)getAttributeInternal(MARKERPOST);
    }

    /**
     * Sets <code>value</code> as attribute value for MARKERPOST using the alias name Markerpost.
     * @param value value to set the MARKERPOST
     */
    public void setMarkerpost(String value) {
        setAttributeInternal(MARKERPOST, value);
    }

    /**
     * Gets the attribute value for RP_FOR_ID using the alias name RpForId.
     * @return the RP_FOR_ID
     */
    public String getRpForId() {
        return (String)getAttributeInternal(RPFORID);
    }

    /**
     * Sets <code>value</code> as attribute value for RP_FOR_ID using the alias name RpForId.
     * @param value value to set the RP_FOR_ID
     */
    public void setRpForId(String value) {
        setAttributeInternal(RPFORID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalPieces.
     * @return the TotalPieces
     */
    public Number getTotalPieces() {
        //return (Number) getAttributeInternal(TOTALPIECES);
        oracle.jbo.domain.Number total = new oracle.jbo.domain.Number(0);
        oracle.jbo.domain.Number rowValue = new oracle.jbo.domain.Number(0);
        RowSetIterator iter = getViewObject().createRowSetIterator("abc");
        while (iter.hasNext()) {
            oracle.jbo.Row r = iter.next();
            try {
                rowValue =
                        (oracle.jbo.domain.Number)r.getAttribute("Totalpcs");
                if (rowValue != null)
                    total = total.add(rowValue);
            } catch (Exception e) {
                iter.closeRowSetIterator();
            }
        } //end of while loop

        iter.closeRowSetIterator();

        return total;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalPieces.
     * @param value value to set the  TotalPieces
     */
    public void setTotalPieces(Number value) {
        setAttributeInternal(TOTALPIECES, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ToTalLays.
     * @return the ToTalLays
     */
    public Number getToTalLays() {
       // return (Number) getAttributeInternal(TOTALLAYS);
        
       oracle.jbo.domain.Number total = new oracle.jbo.domain.Number(0);
       oracle.jbo.domain.Number rowValue = new oracle.jbo.domain.Number(0);
       RowSetIterator iter = getViewObject().createRowSetIterator("abc");
       while (iter.hasNext()) {
           oracle.jbo.Row r = iter.next();
           try {
               rowValue =
                       (oracle.jbo.domain.Number)r.getAttribute("Ply");
               if (rowValue != null)
                   total = total.add(rowValue);
           } catch (Exception e) {
               iter.closeRowSetIterator();
           }
       } //end of while loop
       iter.closeRowSetIterator();
       
        return total;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ToTalLays.
     * @param value value to set the  ToTalLays
     */
    public void setToTalLays(Number value) {
        setAttributeInternal(TOTALLAYS, value);
    }

    /**
     * Gets the attribute value for CUT_NO using the alias name CutNo.
     * @return the CUT_NO
     */
    public String getCutNo() {
        return (String) getAttributeInternal(CUTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CUT_NO using the alias name CutNo.
     * @param value value to set the CUT_NO
     */
    public void setCutNo(String value) {
        setAttributeInternal(CUTNO, value);
    }

    /**
     * Gets the attribute value for CUT_SR_NO using the alias name CutSrNo.
     * @return the CUT_SR_NO
     */
    public Number getCutSrNo() {
        return (Number) getAttributeInternal(CUTSRNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CUT_SR_NO using the alias name CutSrNo.
     * @param value value to set the CUT_SR_NO
     */
    public void setCutSrNo(Number value) {
        setAttributeInternal(CUTSRNO, value);
    }

    /**
     * Gets the attribute value for SHIP_PRIORITY using the alias name ShipPriority.
     * @return the SHIP_PRIORITY
     */
    public String getShipPriority() {
        return (String) getAttributeInternal(SHIPPRIORITY);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_PRIORITY using the alias name ShipPriority.
     * @param value value to set the SHIP_PRIORITY
     */
    public void setShipPriority(String value) {
        setAttributeInternal(SHIPPRIORITY, value);
    }

    /**
     * Gets the attribute value for PATTERN using the alias name Pattern.
     * @return the PATTERN
     */
    public String getPattern() {
        return (String) getAttributeInternal(PATTERN);
    }

    /**
     * Sets <code>value</code> as attribute value for PATTERN using the alias name Pattern.
     * @param value value to set the PATTERN
     */
    public void setPattern(String value) {
        setAttributeInternal(PATTERN, value);
    }

    /**
     * Gets the attribute value for INSEAM_PATTERN using the alias name InseamPattern.
     * @return the INSEAM_PATTERN
     */
    public String getInseamPattern() {
        return (String) getAttributeInternal(INSEAMPATTERN);
    }

    /**
     * Sets <code>value</code> as attribute value for INSEAM_PATTERN using the alias name InseamPattern.
     * @param value value to set the INSEAM_PATTERN
     */
    public void setInseamPattern(String value) {
        setAttributeInternal(INSEAMPATTERN, value);
    }

    /**
     * Gets the attribute value for TOTAL_INSEAM_QTY using the alias name TotalInseamQty.
     * @return the TOTAL_INSEAM_QTY
     */
    public Number getTotalInseamQty() {
        return (Number) getAttributeInternal(TOTALINSEAMQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_INSEAM_QTY using the alias name TotalInseamQty.
     * @param value value to set the TOTAL_INSEAM_QTY
     */
    public void setTotalInseamQty(Number value) {
        setAttributeInternal(TOTALINSEAMQTY, value);
    }

    /**
     * Gets the attribute value for BLNC_INSEAM_QTY using the alias name BlncInseamQty.
     * @return the BLNC_INSEAM_QTY
     */
    public Number getBlncInseamQty() {
        return (Number) getAttributeInternal(BLNCINSEAMQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for BLNC_INSEAM_QTY using the alias name BlncInseamQty.
     * @param value value to set the BLNC_INSEAM_QTY
     */
    public void setBlncInseamQty(Number value) {
        setAttributeInternal(BLNCINSEAMQTY, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link MnjMfgRatioplanPlycflineView.
     */
    public RowIterator getMnjMfgRatioplanPlycflineView() {
        return (RowIterator)getAttributeInternal(MNJMFGRATIOPLANPLYCFLINEVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link MnjMfgRatioplanSizlineView.
     */
    public RowIterator getMnjMfgRatioplanSizlineView() {
        return (RowIterator)getAttributeInternal(MNJMFGRATIOPLANSIZLINEVIEW);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link MarkerLayPlanVO.
     */
    public RowIterator getMarkerLayPlanVO() {
        return (RowIterator)getAttributeInternal(MARKERLAYPLANVO);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BundleDetailVO.
     */
    public RowIterator getBundleDetailVO() {
        return (RowIterator)getAttributeInternal(BUNDLEDETAILVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ShipPriorityVO1.
     */
    public RowSet getShipPriorityVO1() {
        return (RowSet)getAttributeInternal(SHIPPRIORITYVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> InseamSizeQualityPlanVO1.
     */
    public RowSet getInseamSizeQualityPlanVO1() {
        return (RowSet)getAttributeInternal(INSEAMSIZEQUALITYPLANVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> NewInseamLOV1.
     */
    public RowSet getNewInseamLOV1() {
        return (RowSet)getAttributeInternal(NEWINSEAMLOV1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
