package mnj.mfg.model.services.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 31 17:08:49 PKT 2015
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    String callCreateRouting(int inventoryID, int rationPlanID);

    String callBOM(int inventoryID, int rationPlanID);

    String callItem(int inventoryID, int rationPlanID);

    void setValues();


    String createJob(int rationPlanID);

    String populateSTNs(String saleOrderId);

    void setSTNWhereClause(String saleOrderId);

    void PopulateSize();


    double getPreSizeBlnc(String rationPlanID, String sizeVal, String sizeId);

    void refreshSizeBlnc(String rationPlanID, String sizeVal, String sizeId);

    void makeBundles();

    void createCutNos();

    void createCutNosNew();

    void setSessionValues(String orgId, String userId, String respId,
                          String respAppl);

    void setBPOWhereClause();

    void popBPO();

    void copySize();

    void popRollNo();

    double getPlanQty(String rationPlanID);

    void setSTNWhereClause();

    void popSTN();

    void selectAllLines(String flag);

    void setPopulateSizeWhereClause(String inseam);

    void TotalBalanceQuantity();

    String UpdateJobQuantity();

    void populateBundlesParts();

    void RefreshBlocks();

    String CalculateResource(String rationPlanID);

    String AssignSubInventories(String rationPlanID);
}
