package mnj.mfg.model.entities;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 22 11:27:52 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MarkerLayplanDetImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    @Override
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MNJ_MFG_MARKER_LAYPLAN_DET_S",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setDetailId(sVal);
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DetailId {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getDetailId();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setDetailId((Number)value);
            }
        }
        ,
        PlylineId {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getPlylineId();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setPlylineId((Number)value);
            }
        }
        ,
        ReceiptNo {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getReceiptNo();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setReceiptNo((String)value);
            }
        }
        ,
        MarkerNo {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getMarkerNo();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setMarkerNo((String)value);
            }
        }
        ,
        MarkLength {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getMarkLength();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setMarkLength((Number)value);
            }
        }
        ,
        MarkLengthUom {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getMarkLengthUom();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setMarkLengthUom((String)value);
            }
        }
        ,
        MarkWidth {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getMarkWidth();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setMarkWidth((Number)value);
            }
        }
        ,
        MarkWidthUom {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getMarkWidthUom();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setMarkWidthUom((String)value);
            }
        }
        ,
        RollNo {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getRollNo();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setRollNo((String)value);
            }
        }
        ,
        RatioQty {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getRatioQty();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setRatioQty((Number)value);
            }
        }
        ,
        FabricContain {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getFabricContain();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setFabricContain((Number)value);
            }
        }
        ,
        FabContUom {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getFabContUom();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setFabContUom((String)value);
            }
        }
        ,
        FabWidth {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getFabWidth();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setFabWidth((Number)value);
            }
        }
        ,
        FabGsm {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getFabGsm();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setFabGsm((Number)value);
            }
        }
        ,
        FabGsmUom {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getFabGsmUom();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setFabGsmUom((String)value);
            }
        }
        ,
        ShrinkPrcnt {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getShrinkPrcnt();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setShrinkPrcnt((String)value);
            }
        }
        ,
        Shade {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getShade();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setShade((String)value);
            }
        }
        ,
        Lay {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getLay();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setLay((Number)value);
            }
        }
        ,
        LayRemQty {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getLayRemQty();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setLayRemQty((Number)value);
            }
        }
        ,
        EndBit {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getEndBit();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setEndBit((Number)value);
            }
        }
        ,
        EndBitUom {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getEndBitUom();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setEndBitUom((String)value);
            }
        }
        ,
        CutQty {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getCutQty();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setCutQty((Number)value);
            }
        }
        ,
        CutQtyUom {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getCutQtyUom();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setCutQtyUom((String)value);
            }
        }
        ,
        CutRemQty {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getCutRemQty();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setCutRemQty((Number)value);
            }
        }
        ,
        CutRemQtyUom {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getCutRemQtyUom();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setCutRemQtyUom((String)value);
            }
        }
        ,
        RatioplanId {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getRatioplanId();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setRatioplanId((Number)value);
            }
        }
        ,
        MarkLength2 {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getMarkLength2();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setMarkLength2((Number)value);
            }
        }
        ,
        MarkLengthUom2 {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getMarkLengthUom2();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setMarkLengthUom2((String)value);
            }
        }
        ,
        EndBit2 {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getEndBit2();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setEndBit2((Number)value);
            }
        }
        ,
        EndBitUom2 {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getEndBitUom2();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setEndBitUom2((String)value);
            }
        }
        ,
        PlycflineId {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getPlycflineId();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setPlycflineId((Number)value);
            }
        }
        ,
        FabConInch {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getFabConInch();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setFabConInch((Number)value);
            }
        }
        ,
        FabConInchUom {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getFabConInchUom();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setFabConInchUom((String)value);
            }
        }
        ,
        CutWidth {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getCutWidth();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setCutWidth((Number)value);
            }
        }
        ,
        ShrinkPattern {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getShrinkPattern();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setShrinkPattern((String)value);
            }
        }
        ,
        RequisitionReqId {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getRequisitionReqId();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setRequisitionReqId((Number)value);
            }
        }
        ,
        GenerateRequisition {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getGenerateRequisition();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setGenerateRequisition((String)value);
            }
        }
        ,
        SupplierRollNo {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getSupplierRollNo();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setSupplierRollNo((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        MnjMfgRatioplanPlycfline {
            public Object get(MarkerLayplanDetImpl obj) {
                return obj.getMnjMfgRatioplanPlycfline();
            }

            public void put(MarkerLayplanDetImpl obj, Object value) {
                obj.setMnjMfgRatioplanPlycfline((MnjMfgRatioplanPlycflineImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MarkerLayplanDetImpl object);

        public abstract void put(MarkerLayplanDetImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

   // public static final int MNJMFGRATIOPLANPLYLINE1 = AttributesEnum.MnjMfgRatioplanPlyline1.index();


//    public static final int MNJMFGRATIOPLANPLYLINE = AttributesEnum.MnjMfgRatioplanPlyline.index();


    public static final int DETAILID = AttributesEnum.DetailId.index();
    public static final int PLYLINEID = AttributesEnum.PlylineId.index();
    public static final int RECEIPTNO = AttributesEnum.ReceiptNo.index();
    public static final int MARKERNO = AttributesEnum.MarkerNo.index();
    public static final int MARKLENGTH = AttributesEnum.MarkLength.index();
    public static final int MARKLENGTHUOM = AttributesEnum.MarkLengthUom.index();
    public static final int MARKWIDTH = AttributesEnum.MarkWidth.index();
    public static final int MARKWIDTHUOM = AttributesEnum.MarkWidthUom.index();
    public static final int ROLLNO = AttributesEnum.RollNo.index();
    public static final int RATIOQTY = AttributesEnum.RatioQty.index();
    public static final int FABRICCONTAIN = AttributesEnum.FabricContain.index();
    public static final int FABCONTUOM = AttributesEnum.FabContUom.index();
    public static final int FABWIDTH = AttributesEnum.FabWidth.index();
    public static final int FABGSM = AttributesEnum.FabGsm.index();
    public static final int FABGSMUOM = AttributesEnum.FabGsmUom.index();
    public static final int SHRINKPRCNT = AttributesEnum.ShrinkPrcnt.index();
    public static final int SHADE = AttributesEnum.Shade.index();
    public static final int LAY = AttributesEnum.Lay.index();
    public static final int LAYREMQTY = AttributesEnum.LayRemQty.index();
    public static final int ENDBIT = AttributesEnum.EndBit.index();
    public static final int ENDBITUOM = AttributesEnum.EndBitUom.index();
    public static final int CUTQTY = AttributesEnum.CutQty.index();
    public static final int CUTQTYUOM = AttributesEnum.CutQtyUom.index();
    public static final int CUTREMQTY = AttributesEnum.CutRemQty.index();
    public static final int CUTREMQTYUOM = AttributesEnum.CutRemQtyUom.index();
    public static final int RATIOPLANID = AttributesEnum.RatioplanId.index();
    public static final int MARKLENGTH2 = AttributesEnum.MarkLength2.index();
    public static final int MARKLENGTHUOM2 = AttributesEnum.MarkLengthUom2.index();
    public static final int ENDBIT2 = AttributesEnum.EndBit2.index();
    public static final int ENDBITUOM2 = AttributesEnum.EndBitUom2.index();
    public static final int PLYCFLINEID = AttributesEnum.PlycflineId.index();
    public static final int FABCONINCH = AttributesEnum.FabConInch.index();
    public static final int FABCONINCHUOM = AttributesEnum.FabConInchUom.index();
    public static final int CUTWIDTH = AttributesEnum.CutWidth.index();
    public static final int SHRINKPATTERN = AttributesEnum.ShrinkPattern.index();
    public static final int REQUISITIONREQID = AttributesEnum.RequisitionReqId.index();
    public static final int GENERATEREQUISITION = AttributesEnum.GenerateRequisition.index();
    public static final int SUPPLIERROLLNO = AttributesEnum.SupplierRollNo.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int MNJMFGRATIOPLANPLYCFLINE = AttributesEnum.MnjMfgRatioplanPlycfline.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MarkerLayplanDetImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.MarkerLayplanDet");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for DetailId, using the alias name DetailId.
     * @return the DetailId
     */
    public Number getDetailId() {
        return (Number)getAttributeInternal(DETAILID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DetailId.
     * @param value value to set the DetailId
     */
    public void setDetailId(Number value) {
        setAttributeInternal(DETAILID, value);
    }

    /**
     * Gets the attribute value for PlylineId, using the alias name PlylineId.
     * @return the PlylineId
     */
    public Number getPlylineId() {
        return (Number)getAttributeInternal(PLYLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlylineId.
     * @param value value to set the PlylineId
     */
    public void setPlylineId(Number value) {
        setAttributeInternal(PLYLINEID, value);
    }

    /**
     * Gets the attribute value for ReceiptNo, using the alias name ReceiptNo.
     * @return the ReceiptNo
     */
    public String getReceiptNo() {
        return (String)getAttributeInternal(RECEIPTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReceiptNo.
     * @param value value to set the ReceiptNo
     */
    public void setReceiptNo(String value) {
        setAttributeInternal(RECEIPTNO, value);
    }

    /**
     * Gets the attribute value for MarkerNo, using the alias name MarkerNo.
     * @return the MarkerNo
     */
    public String getMarkerNo() {
        return (String)getAttributeInternal(MARKERNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for MarkerNo.
     * @param value value to set the MarkerNo
     */
    public void setMarkerNo(String value) {
        setAttributeInternal(MARKERNO, value);
    }

    /**
     * Gets the attribute value for MarkLength, using the alias name MarkLength.
     * @return the MarkLength
     */
    public Number getMarkLength() {
        return (Number)getAttributeInternal(MARKLENGTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for MarkLength.
     * @param value value to set the MarkLength
     */
    public void setMarkLength(Number value) {
        setAttributeInternal(MARKLENGTH, value);
    }

    /**
     * Gets the attribute value for MarkLengthUom, using the alias name MarkLengthUom.
     * @return the MarkLengthUom
     */
    public String getMarkLengthUom() {
        return (String)getAttributeInternal(MARKLENGTHUOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for MarkLengthUom.
     * @param value value to set the MarkLengthUom
     */
    public void setMarkLengthUom(String value) {
        setAttributeInternal(MARKLENGTHUOM, value);
    }

    /**
     * Gets the attribute value for MarkWidth, using the alias name MarkWidth.
     * @return the MarkWidth
     */
    public Number getMarkWidth() {
        return (Number)getAttributeInternal(MARKWIDTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for MarkWidth.
     * @param value value to set the MarkWidth
     */
    public void setMarkWidth(Number value) {
        setAttributeInternal(MARKWIDTH, value);
    }

    /**
     * Gets the attribute value for MarkWidthUom, using the alias name MarkWidthUom.
     * @return the MarkWidthUom
     */
    public String getMarkWidthUom() {
        return (String)getAttributeInternal(MARKWIDTHUOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for MarkWidthUom.
     * @param value value to set the MarkWidthUom
     */
    public void setMarkWidthUom(String value) {
        setAttributeInternal(MARKWIDTHUOM, value);
    }

    /**
     * Gets the attribute value for RollNo, using the alias name RollNo.
     * @return the RollNo
     */
    public String getRollNo() {
        return (String)getAttributeInternal(ROLLNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for RollNo.
     * @param value value to set the RollNo
     */
    public void setRollNo(String value) {
        setAttributeInternal(ROLLNO, value);
    }

    /**
     * Gets the attribute value for RatioQty, using the alias name RatioQty.
     * @return the RatioQty
     */
    public Number getRatioQty() {
        return (Number)getAttributeInternal(RATIOQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for RatioQty.
     * @param value value to set the RatioQty
     */
    public void setRatioQty(Number value) {
        setAttributeInternal(RATIOQTY, value);
    }

    /**
     * Gets the attribute value for FabricContain, using the alias name FabricContain.
     * @return the FabricContain
     */
    public Number getFabricContain() {
        return (Number)getAttributeInternal(FABRICCONTAIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabricContain.
     * @param value value to set the FabricContain
     */
    public void setFabricContain(Number value) {
        setAttributeInternal(FABRICCONTAIN, value);
    }

    /**
     * Gets the attribute value for FabContUom, using the alias name FabContUom.
     * @return the FabContUom
     */
    public String getFabContUom() {
        return (String)getAttributeInternal(FABCONTUOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabContUom.
     * @param value value to set the FabContUom
     */
    public void setFabContUom(String value) {
        setAttributeInternal(FABCONTUOM, value);
    }

    /**
     * Gets the attribute value for FabWidth, using the alias name FabWidth.
     * @return the FabWidth
     */
    public Number getFabWidth() {
        return (Number)getAttributeInternal(FABWIDTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabWidth.
     * @param value value to set the FabWidth
     */
    public void setFabWidth(Number value) {
        setAttributeInternal(FABWIDTH, value);
    }

    /**
     * Gets the attribute value for FabGsm, using the alias name FabGsm.
     * @return the FabGsm
     */
    public Number getFabGsm() {
        return (Number)getAttributeInternal(FABGSM);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabGsm.
     * @param value value to set the FabGsm
     */
    public void setFabGsm(Number value) {
        setAttributeInternal(FABGSM, value);
    }

    /**
     * Gets the attribute value for FabGsmUom, using the alias name FabGsmUom.
     * @return the FabGsmUom
     */
    public String getFabGsmUom() {
        return (String)getAttributeInternal(FABGSMUOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabGsmUom.
     * @param value value to set the FabGsmUom
     */
    public void setFabGsmUom(String value) {
        setAttributeInternal(FABGSMUOM, value);
    }

    /**
     * Gets the attribute value for ShrinkPrcnt, using the alias name ShrinkPrcnt.
     * @return the ShrinkPrcnt
     */
    public String getShrinkPrcnt() {
        return (String)getAttributeInternal(SHRINKPRCNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShrinkPrcnt.
     * @param value value to set the ShrinkPrcnt
     */
    public void setShrinkPrcnt(String value) {
        setAttributeInternal(SHRINKPRCNT, value);
    }

    /**
     * Gets the attribute value for Shade, using the alias name Shade.
     * @return the Shade
     */
    public String getShade() {
        return (String)getAttributeInternal(SHADE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Shade.
     * @param value value to set the Shade
     */
    public void setShade(String value) {
        setAttributeInternal(SHADE, value);
    }

    /**
     * Gets the attribute value for Lay, using the alias name Lay.
     * @return the Lay
     */
    public Number getLay() {
        return (Number)getAttributeInternal(LAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Lay.
     * @param value value to set the Lay
     */
    public void setLay(Number value) {
        setAttributeInternal(LAY, value);
    }

    /**
     * Gets the attribute value for LayRemQty, using the alias name LayRemQty.
     * @return the LayRemQty
     */
    public Number getLayRemQty() {
        return (Number)getAttributeInternal(LAYREMQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LayRemQty.
     * @param value value to set the LayRemQty
     */
    public void setLayRemQty(Number value) {
        setAttributeInternal(LAYREMQTY, value);
    }

    /**
     * Gets the attribute value for EndBit, using the alias name EndBit.
     * @return the EndBit
     */
    public Number getEndBit() {
        return (Number)getAttributeInternal(ENDBIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for EndBit.
     * @param value value to set the EndBit
     */
    public void setEndBit(Number value) {
        setAttributeInternal(ENDBIT, value);
    }

    /**
     * Gets the attribute value for EndBitUom, using the alias name EndBitUom.
     * @return the EndBitUom
     */
    public String getEndBitUom() {
        return (String)getAttributeInternal(ENDBITUOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for EndBitUom.
     * @param value value to set the EndBitUom
     */
    public void setEndBitUom(String value) {
        setAttributeInternal(ENDBITUOM, value);
    }

    /**
     * Gets the attribute value for CutQty, using the alias name CutQty.
     * @return the CutQty
     */
    public Number getCutQty() {
        return (Number)getAttributeInternal(CUTQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutQty.
     * @param value value to set the CutQty
     */
    public void setCutQty(Number value) {
        setAttributeInternal(CUTQTY, value);
    }

    /**
     * Gets the attribute value for CutQtyUom, using the alias name CutQtyUom.
     * @return the CutQtyUom
     */
    public String getCutQtyUom() {
        return (String)getAttributeInternal(CUTQTYUOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutQtyUom.
     * @param value value to set the CutQtyUom
     */
    public void setCutQtyUom(String value) {
        setAttributeInternal(CUTQTYUOM, value);
    }

    /**
     * Gets the attribute value for CutRemQty, using the alias name CutRemQty.
     * @return the CutRemQty
     */
    public Number getCutRemQty() {
        return (Number)getAttributeInternal(CUTREMQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutRemQty.
     * @param value value to set the CutRemQty
     */
    public void setCutRemQty(Number value) {
        setAttributeInternal(CUTREMQTY, value);
    }

    /**
     * Gets the attribute value for CutRemQtyUom, using the alias name CutRemQtyUom.
     * @return the CutRemQtyUom
     */
    public String getCutRemQtyUom() {
        return (String)getAttributeInternal(CUTREMQTYUOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutRemQtyUom.
     * @param value value to set the CutRemQtyUom
     */
    public void setCutRemQtyUom(String value) {
        setAttributeInternal(CUTREMQTYUOM, value);
    }

    /**
     * Gets the attribute value for RatioplanId, using the alias name RatioplanId.
     * @return the RatioplanId
     */
    public Number getRatioplanId() {
        return (Number)getAttributeInternal(RATIOPLANID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RatioplanId.
     * @param value value to set the RatioplanId
     */
    public void setRatioplanId(Number value) {
        setAttributeInternal(RATIOPLANID, value);
    }

    /**
     * Gets the attribute value for MarkLength2, using the alias name MarkLength2.
     * @return the MarkLength2
     */
    public Number getMarkLength2() {
        return (Number)getAttributeInternal(MARKLENGTH2);
    }

    /**
     * Sets <code>value</code> as the attribute value for MarkLength2.
     * @param value value to set the MarkLength2
     */
    public void setMarkLength2(Number value) {
        setAttributeInternal(MARKLENGTH2, value);
    }

    /**
     * Gets the attribute value for MarkLengthUom2, using the alias name MarkLengthUom2.
     * @return the MarkLengthUom2
     */
    public String getMarkLengthUom2() {
        return (String)getAttributeInternal(MARKLENGTHUOM2);
    }

    /**
     * Sets <code>value</code> as the attribute value for MarkLengthUom2.
     * @param value value to set the MarkLengthUom2
     */
    public void setMarkLengthUom2(String value) {
        setAttributeInternal(MARKLENGTHUOM2, value);
    }

    /**
     * Gets the attribute value for EndBit2, using the alias name EndBit2.
     * @return the EndBit2
     */
    public Number getEndBit2() {
        return (Number)getAttributeInternal(ENDBIT2);
    }

    /**
     * Sets <code>value</code> as the attribute value for EndBit2.
     * @param value value to set the EndBit2
     */
    public void setEndBit2(Number value) {
        setAttributeInternal(ENDBIT2, value);
    }

    /**
     * Gets the attribute value for EndBitUom2, using the alias name EndBitUom2.
     * @return the EndBitUom2
     */
    public String getEndBitUom2() {
        return (String)getAttributeInternal(ENDBITUOM2);
    }

    /**
     * Sets <code>value</code> as the attribute value for EndBitUom2.
     * @param value value to set the EndBitUom2
     */
    public void setEndBitUom2(String value) {
        setAttributeInternal(ENDBITUOM2, value);
    }

    /**
     * Gets the attribute value for PlycflineId, using the alias name PlycflineId.
     * @return the PlycflineId
     */
    public Number getPlycflineId() {
        return (Number)getAttributeInternal(PLYCFLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlycflineId.
     * @param value value to set the PlycflineId
     */
    public void setPlycflineId(Number value) {
        setAttributeInternal(PLYCFLINEID, value);
    }

    /**
     * Gets the attribute value for FabConInch, using the alias name FabConInch.
     * @return the FabConInch
     */
    public Number getFabConInch() {
        return (Number)getAttributeInternal(FABCONINCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabConInch.
     * @param value value to set the FabConInch
     */
    public void setFabConInch(Number value) {
        setAttributeInternal(FABCONINCH, value);
    }

    /**
     * Gets the attribute value for FabConInchUom, using the alias name FabConInchUom.
     * @return the FabConInchUom
     */
    public String getFabConInchUom() {
        return (String)getAttributeInternal(FABCONINCHUOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabConInchUom.
     * @param value value to set the FabConInchUom
     */
    public void setFabConInchUom(String value) {
        setAttributeInternal(FABCONINCHUOM, value);
    }

    /**
     * Gets the attribute value for CutWidth, using the alias name CutWidth.
     * @return the CutWidth
     */
    public Number getCutWidth() {
        return (Number)getAttributeInternal(CUTWIDTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutWidth.
     * @param value value to set the CutWidth
     */
    public void setCutWidth(Number value) {
        setAttributeInternal(CUTWIDTH, value);
    }

    /**
     * Gets the attribute value for ShrinkPattern, using the alias name ShrinkPattern.
     * @return the ShrinkPattern
     */
    public String getShrinkPattern() {
        return (String)getAttributeInternal(SHRINKPATTERN);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShrinkPattern.
     * @param value value to set the ShrinkPattern
     */
    public void setShrinkPattern(String value) {
        setAttributeInternal(SHRINKPATTERN, value);
    }

    /**
     * Gets the attribute value for RequisitionReqId, using the alias name RequisitionReqId.
     * @return the RequisitionReqId
     */
    public Number getRequisitionReqId() {
        return (Number)getAttributeInternal(REQUISITIONREQID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequisitionReqId.
     * @param value value to set the RequisitionReqId
     */
    public void setRequisitionReqId(Number value) {
        setAttributeInternal(REQUISITIONREQID, value);
    }

    /**
     * Gets the attribute value for GenerateRequisition, using the alias name GenerateRequisition.
     * @return the GenerateRequisition
     */
    public String getGenerateRequisition() {
        return (String)getAttributeInternal(GENERATEREQUISITION);
    }

    /**
     * Sets <code>value</code> as the attribute value for GenerateRequisition.
     * @param value value to set the GenerateRequisition
     */
    public void setGenerateRequisition(String value) {
        setAttributeInternal(GENERATEREQUISITION, value);
    }

    /**
     * Gets the attribute value for SupplierRollNo, using the alias name SupplierRollNo.
     * @return the SupplierRollNo
     */
    public String getSupplierRollNo() {
        return (String)getAttributeInternal(SUPPLIERROLLNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupplierRollNo.
     * @param value value to set the SupplierRollNo
     */
    public void setSupplierRollNo(String value) {
        setAttributeInternal(SUPPLIERROLLNO, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity MnjMfgRatioplanPlylineImpl.
     */
//    public MnjMfgRatioplanPlylineImpl getMnjMfgRatioplanPlyline() {
//        return (MnjMfgRatioplanPlylineImpl)getAttributeInternal(MNJMFGRATIOPLANPLYLINE);
//    }

    /**
     * Sets <code>value</code> as the associated entity MnjMfgRatioplanPlylineImpl.
     */
//    public void setMnjMfgRatioplanPlyline(MnjMfgRatioplanPlylineImpl value) {
//        setAttributeInternal(MNJMFGRATIOPLANPLYLINE, value);
//    }

    /**
     * @return the associated entity MnjMfgRatioplanPlycflineImpl.
     */
    public MnjMfgRatioplanPlycflineImpl getMnjMfgRatioplanPlycfline() {
        return (MnjMfgRatioplanPlycflineImpl)getAttributeInternal(MNJMFGRATIOPLANPLYCFLINE);
    }

    /**
     * Sets <code>value</code> as the associated entity MnjMfgRatioplanPlycflineImpl.
     */
    public void setMnjMfgRatioplanPlycfline(MnjMfgRatioplanPlycflineImpl value) {
        setAttributeInternal(MNJMFGRATIOPLANPLYCFLINE, value);
    }

    /**
     * @param detailId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number detailId) {
        return new Key(new Object[]{detailId});
    }


    /**
     * @return the associated entity MnjMfgRatioplanPlylineImpl.
     */
//    public MnjMfgRatioplanPlylineImpl getMnjMfgRatioplanPlyline1() {
//        return (MnjMfgRatioplanPlylineImpl)getAttributeInternal(MNJMFGRATIOPLANPLYLINE1);
//    }

    /**
     * Sets <code>value</code> as the associated entity MnjMfgRatioplanPlylineImpl.
     */
//    public void setMnjMfgRatioplanPlyline1(MnjMfgRatioplanPlylineImpl value) {
//        setAttributeInternal(MNJMFGRATIOPLANPLYLINE1, value);
//    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Map sessionScope = ADFContext.getCurrent().getSessionScope();   
        String user = (String)sessionScope.get("userId");
        String orgId  =(String)sessionScope.get("orgId");
        String unitName  =(String)sessionScope.get("unitName");
        
        System.out.println("ASSES INS DO DML 1 ------------------>"+user);
        System.out.println("ASSES INS DO DML 2------------------>"+orgId);
        System.out.println("ASSES INS DML 3 ------------------>"+unitName);
        
        if(DML_UPDATE == operation){
                  try {
                      
                      setLastUpdateDate((Date)Date.getCurrentDate()); 
                      setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                  } catch (SQLException f) {
                      System.out.println(f.getMessage());
                  }
              }
              else if (DML_INSERT == operation){
               
                  try {
                      
                      //setHeaderNo(getSrNoString());
                      //setOrgId(new oracle.jbo.domain.Number(orgId));
                      //setAttribute1(unitName);
                      setCreationDate((Date)Date.getCurrentDate());  
                      setCreatedBy(new oracle.jbo.domain.Number(user));
                     
                     
                     
                  } catch (SQLException f) {
                      ;
                  }
              } 
        
        super.doDML(operation, e);
    }


}
