package mnj.mfg.model.entities;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 26 17:24:44 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgRatioplanImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DivisionId {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getDivisionId();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setDivisionId((String)value);
            }
        }
        ,
        RatioplanId {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getRatioplanId();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setRatioplanId((Number)value);
            }
        }
        ,
        RatioplanNumber {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getRatioplanNumber();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setRatioplanNumber((String)value);
            }
        }
        ,
        RatioplanDate {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getRatioplanDate();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setRatioplanDate((Date)value);
            }
        }
        ,
        SalesorderId {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getSalesorderId();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setSalesorderId((Number)value);
            }
        }
        ,
        ItemCode {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getItemCode();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setItemCode((String)value);
            }
        }
        ,
        Obsno {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getObsno();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setObsno((String)value);
            }
        }
        ,
        Obsnoold {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getObsnoold();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setObsnoold((String)value);
            }
        }
        ,
        Inseams {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getInseams();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setInseams((String)value);
            }
        }
        ,
        ExtraCutPercent {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getExtraCutPercent();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setExtraCutPercent((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getRemarks();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        Plantype {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getPlantype();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setPlantype((String)value);
            }
        }
        ,
        Planstatus {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getPlanstatus();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setPlanstatus((String)value);
            }
        }
        ,
        Typeplan {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getTypeplan();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setTypeplan((String)value);
            }
        }
        ,
        ActualExtraPercent {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getActualExtraPercent();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setActualExtraPercent((Number)value);
            }
        }
        ,
        ToleranceExtraPercent {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getToleranceExtraPercent();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setToleranceExtraPercent((Number)value);
            }
        }
        ,
        InventoryItemId {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getInventoryItemId();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setInventoryItemId((Number)value);
            }
        }
        ,
        OrderLineId {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getOrderLineId();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setOrderLineId((Number)value);
            }
        }
        ,
        InseamLineId {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getInseamLineId();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setInseamLineId((Number)value);
            }
        }
        ,
        JobStatus {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getJobStatus();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setJobStatus((String)value);
            }
        }
        ,
        TotalQty {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getTotalQty();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setTotalQty((Number)value);
            }
        }
        ,
        BuyerId {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getBuyerId();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        Style {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getStyle();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setStyle((String)value);
            }
        }
        ,
        BpoNo {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getBpoNo();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setBpoNo((String)value);
            }
        }
        ,
        Color {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getColor();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setColor((String)value);
            }
        }
        ,
        MinEndBit {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getMinEndBit();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setMinEndBit((Number)value);
            }
        }
        ,
        MinBndSize {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getMinBndSize();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setMinBndSize((Number)value);
            }
        }
        ,
        MaxBndSize {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getMaxBndSize();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setMaxBndSize((Number)value);
            }
        }
        ,
        Season {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getSeason();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        Deviation {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getDeviation();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setDeviation((Number)value);
            }
        }
        ,
        DeviatonPrcnt {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getDeviatonPrcnt();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setDeviatonPrcnt((Number)value);
            }
        }
        ,
        OrderQty {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getOrderQty();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setOrderQty((Number)value);
            }
        }
        ,
        CutQty {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getCutQty();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setCutQty((Number)value);
            }
        }
        ,
        PlanDev {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getPlanDev();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setPlanDev((Number)value);
            }
        }
        ,
        PlanDevPrcnt {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getPlanDevPrcnt();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setPlanDevPrcnt((Number)value);
            }
        }
        ,
        Unit {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getUnit();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setUnit((String)value);
            }
        }
        ,
        Osp {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getOsp();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setOsp((String)value);
            }
        }
        ,
        OspUnit {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getOspUnit();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setOspUnit((String)value);
            }
        }
        ,
        Printing {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getPrinting();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setPrinting((String)value);
            }
        }
        ,
        Embriodry {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getEmbriodry();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setEmbriodry((String)value);
            }
        }
        ,
        LastAction {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getLastAction();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setLastAction((String)value);
            }
        }
        ,
        RatioPlanQty {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getRatioPlanQty();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setRatioPlanQty((Number)value);
            }
        }
        ,
        ColorId {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getColorId();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setColorId((String)value);
            }
        }
        ,
        BookingConsumption {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getBookingConsumption();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setBookingConsumption((Number)value);
            }
        }
        ,
        ProductionConsumption {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getProductionConsumption();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setProductionConsumption((Number)value);
            }
        }
        ,
        FinishedGarmentsColor {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getFinishedGarmentsColor();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setFinishedGarmentsColor((String)value);
            }
        }
        ,
        Wash {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getWash();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setWash((String)value);
            }
        }
        ,
        SystemId {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getSystemId();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setSystemId((Number)value);
            }
        }
        ,
        PocId {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getPocId();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setPocId((Number)value);
            }
        }
        ,
        MnjMfgRatioplanObline {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getMnjMfgRatioplanObline();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjMfgRatioplanPlyline {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getMnjMfgRatioplanPlyline();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjMfgRatioplanBposAll {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getMnjMfgRatioplanBposAll();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjMfgRatioplanStnsAll {
            public Object get(MnjMfgRatioplanImpl obj) {
                return obj.getMnjMfgRatioplanStnsAll();
            }

            public void put(MnjMfgRatioplanImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjMfgRatioplanImpl object);

        public abstract void put(MnjMfgRatioplanImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int RATIOPLANID = AttributesEnum.RatioplanId.index();
    public static final int RATIOPLANNUMBER = AttributesEnum.RatioplanNumber.index();
    public static final int RATIOPLANDATE = AttributesEnum.RatioplanDate.index();
    public static final int SALESORDERID = AttributesEnum.SalesorderId.index();
    public static final int ITEMCODE = AttributesEnum.ItemCode.index();
    public static final int OBSNO = AttributesEnum.Obsno.index();
    public static final int OBSNOOLD = AttributesEnum.Obsnoold.index();
    public static final int INSEAMS = AttributesEnum.Inseams.index();
    public static final int EXTRACUTPERCENT = AttributesEnum.ExtraCutPercent.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int PLANTYPE = AttributesEnum.Plantype.index();
    public static final int PLANSTATUS = AttributesEnum.Planstatus.index();
    public static final int TYPEPLAN = AttributesEnum.Typeplan.index();
    public static final int ACTUALEXTRAPERCENT = AttributesEnum.ActualExtraPercent.index();
    public static final int TOLERANCEEXTRAPERCENT = AttributesEnum.ToleranceExtraPercent.index();
    public static final int INVENTORYITEMID = AttributesEnum.InventoryItemId.index();
    public static final int ORDERLINEID = AttributesEnum.OrderLineId.index();
    public static final int INSEAMLINEID = AttributesEnum.InseamLineId.index();
    public static final int JOBSTATUS = AttributesEnum.JobStatus.index();
    public static final int TOTALQTY = AttributesEnum.TotalQty.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int STYLE = AttributesEnum.Style.index();
    public static final int BPONO = AttributesEnum.BpoNo.index();
    public static final int COLOR = AttributesEnum.Color.index();
    public static final int MINENDBIT = AttributesEnum.MinEndBit.index();
    public static final int MINBNDSIZE = AttributesEnum.MinBndSize.index();
    public static final int MAXBNDSIZE = AttributesEnum.MaxBndSize.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int DEVIATION = AttributesEnum.Deviation.index();
    public static final int DEVIATONPRCNT = AttributesEnum.DeviatonPrcnt.index();
    public static final int ORDERQTY = AttributesEnum.OrderQty.index();
    public static final int CUTQTY = AttributesEnum.CutQty.index();
    public static final int PLANDEV = AttributesEnum.PlanDev.index();
    public static final int PLANDEVPRCNT = AttributesEnum.PlanDevPrcnt.index();
    public static final int UNIT = AttributesEnum.Unit.index();
    public static final int OSP = AttributesEnum.Osp.index();
    public static final int OSPUNIT = AttributesEnum.OspUnit.index();
    public static final int PRINTING = AttributesEnum.Printing.index();
    public static final int EMBRIODRY = AttributesEnum.Embriodry.index();
    public static final int LASTACTION = AttributesEnum.LastAction.index();
    public static final int RATIOPLANQTY = AttributesEnum.RatioPlanQty.index();
    public static final int COLORID = AttributesEnum.ColorId.index();
    public static final int BOOKINGCONSUMPTION = AttributesEnum.BookingConsumption.index();
    public static final int PRODUCTIONCONSUMPTION = AttributesEnum.ProductionConsumption.index();
    public static final int FINISHEDGARMENTSCOLOR = AttributesEnum.FinishedGarmentsColor.index();
    public static final int WASH = AttributesEnum.Wash.index();
    public static final int SYSTEMID = AttributesEnum.SystemId.index();
    public static final int POCID = AttributesEnum.PocId.index();
    public static final int MNJMFGRATIOPLANOBLINE = AttributesEnum.MnjMfgRatioplanObline.index();
    public static final int MNJMFGRATIOPLANPLYLINE = AttributesEnum.MnjMfgRatioplanPlyline.index();
    public static final int MNJMFGRATIOPLANBPOSALL = AttributesEnum.MnjMfgRatioplanBposAll.index();
    public static final int MNJMFGRATIOPLANSTNSALL = AttributesEnum.MnjMfgRatioplanStnsAll.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgRatioplanImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.MnjMfgRatioplan");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for DivisionId, using the alias name DivisionId.
     * @return the DivisionId
     */
    public String getDivisionId() {
        return (String)getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DivisionId.
     * @param value value to set the DivisionId
     */
    public void setDivisionId(String value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for RatioplanId, using the alias name RatioplanId.
     * @return the RatioplanId
     */
    public Number getRatioplanId() {
        return (Number)getAttributeInternal(RATIOPLANID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RatioplanId.
     * @param value value to set the RatioplanId
     */
    public void setRatioplanId(Number value) {
        setAttributeInternal(RATIOPLANID, value);
    }

    /**
     * Gets the attribute value for RatioplanNumber, using the alias name RatioplanNumber.
     * @return the RatioplanNumber
     */
    public String getRatioplanNumber() {
        return (String)getAttributeInternal(RATIOPLANNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for RatioplanNumber.
     * @param value value to set the RatioplanNumber
     */
    public void setRatioplanNumber(String value) {
        setAttributeInternal(RATIOPLANNUMBER, value);
    }

    /**
     * Gets the attribute value for RatioplanDate, using the alias name RatioplanDate.
     * @return the RatioplanDate
     */
    public Date getRatioplanDate() {
        return (Date)getAttributeInternal(RATIOPLANDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RatioplanDate.
     * @param value value to set the RatioplanDate
     */
    public void setRatioplanDate(Date value) {
        setAttributeInternal(RATIOPLANDATE, value);
    }

    /**
     * Gets the attribute value for SalesorderId, using the alias name SalesorderId.
     * @return the SalesorderId
     */
    public Number getSalesorderId() {
        return (Number)getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesorderId.
     * @param value value to set the SalesorderId
     */
    public void setSalesorderId(Number value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for ItemCode, using the alias name ItemCode.
     * @return the ItemCode
     */
    public String getItemCode() {
        return (String)getAttributeInternal(ITEMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemCode.
     * @param value value to set the ItemCode
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**
     * Gets the attribute value for Obsno, using the alias name Obsno.
     * @return the Obsno
     */
    public String getObsno() {
        return (String)getAttributeInternal(OBSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Obsno.
     * @param value value to set the Obsno
     */
    public void setObsno(String value) {
        setAttributeInternal(OBSNO, value);
    }

    /**
     * Gets the attribute value for Obsnoold, using the alias name Obsnoold.
     * @return the Obsnoold
     */
    public String getObsnoold() {
        return (String)getAttributeInternal(OBSNOOLD);
    }

    /**
     * Sets <code>value</code> as the attribute value for Obsnoold.
     * @param value value to set the Obsnoold
     */
    public void setObsnoold(String value) {
        setAttributeInternal(OBSNOOLD, value);
    }

    /**
     * Gets the attribute value for Inseams, using the alias name Inseams.
     * @return the Inseams
     */
    public String getInseams() {
        return (String)getAttributeInternal(INSEAMS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Inseams.
     * @param value value to set the Inseams
     */
    public void setInseams(String value) {
        setAttributeInternal(INSEAMS, value);
    }

    /**
     * Gets the attribute value for ExtraCutPercent, using the alias name ExtraCutPercent.
     * @return the ExtraCutPercent
     */
    public Number getExtraCutPercent() {
        return (Number)getAttributeInternal(EXTRACUTPERCENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtraCutPercent.
     * @param value value to set the ExtraCutPercent
     */
    public void setExtraCutPercent(Number value) {
        setAttributeInternal(EXTRACUTPERCENT, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Plantype, using the alias name Plantype.
     * @return the Plantype
     */
    public String getPlantype() {
        return (String)getAttributeInternal(PLANTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Plantype.
     * @param value value to set the Plantype
     */
    public void setPlantype(String value) {
        setAttributeInternal(PLANTYPE, value);
    }

    /**
     * Gets the attribute value for Planstatus, using the alias name Planstatus.
     * @return the Planstatus
     */
    public String getPlanstatus() {
        return (String)getAttributeInternal(PLANSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Planstatus.
     * @param value value to set the Planstatus
     */
    public void setPlanstatus(String value) {
        setAttributeInternal(PLANSTATUS, value);
    }

    /**
     * Gets the attribute value for Typeplan, using the alias name Typeplan.
     * @return the Typeplan
     */
    public String getTypeplan() {
        return (String)getAttributeInternal(TYPEPLAN);
    }

    /**
     * Sets <code>value</code> as the attribute value for Typeplan.
     * @param value value to set the Typeplan
     */
    public void setTypeplan(String value) {
        setAttributeInternal(TYPEPLAN, value);
    }

    /**
     * Gets the attribute value for ActualExtraPercent, using the alias name ActualExtraPercent.
     * @return the ActualExtraPercent
     */
    public Number getActualExtraPercent() {
        return (Number)getAttributeInternal(ACTUALEXTRAPERCENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActualExtraPercent.
     * @param value value to set the ActualExtraPercent
     */
    public void setActualExtraPercent(Number value) {
        setAttributeInternal(ACTUALEXTRAPERCENT, value);
    }

    /**
     * Gets the attribute value for ToleranceExtraPercent, using the alias name ToleranceExtraPercent.
     * @return the ToleranceExtraPercent
     */
    public Number getToleranceExtraPercent() {
        return (Number)getAttributeInternal(TOLERANCEEXTRAPERCENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToleranceExtraPercent.
     * @param value value to set the ToleranceExtraPercent
     */
    public void setToleranceExtraPercent(Number value) {
        setAttributeInternal(TOLERANCEEXTRAPERCENT, value);
    }

    /**
     * Gets the attribute value for InventoryItemId, using the alias name InventoryItemId.
     * @return the InventoryItemId
     */
    public Number getInventoryItemId() {
        return (Number)getAttributeInternal(INVENTORYITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InventoryItemId.
     * @param value value to set the InventoryItemId
     */
    public void setInventoryItemId(Number value) {
        setAttributeInternal(INVENTORYITEMID, value);
    }

    /**
     * Gets the attribute value for OrderLineId, using the alias name OrderLineId.
     * @return the OrderLineId
     */
    public Number getOrderLineId() {
        return (Number)getAttributeInternal(ORDERLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderLineId.
     * @param value value to set the OrderLineId
     */
    public void setOrderLineId(Number value) {
        setAttributeInternal(ORDERLINEID, value);
    }

    /**
     * Gets the attribute value for InseamLineId, using the alias name InseamLineId.
     * @return the InseamLineId
     */
    public Number getInseamLineId() {
        return (Number)getAttributeInternal(INSEAMLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InseamLineId.
     * @param value value to set the InseamLineId
     */
    public void setInseamLineId(Number value) {
        setAttributeInternal(INSEAMLINEID, value);
    }

    /**
     * Gets the attribute value for JobStatus, using the alias name JobStatus.
     * @return the JobStatus
     */
    public String getJobStatus() {
        return (String)getAttributeInternal(JOBSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobStatus.
     * @param value value to set the JobStatus
     */
    public void setJobStatus(String value) {
        setAttributeInternal(JOBSTATUS, value);
    }

    /**
     * Gets the attribute value for TotalQty, using the alias name TotalQty.
     * @return the TotalQty
     */
    public Number getTotalQty() {
        return (Number)getAttributeInternal(TOTALQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalQty.
     * @param value value to set the TotalQty
     */
    public void setTotalQty(Number value) {
        setAttributeInternal(TOTALQTY, value);
    }

    /**
     * Gets the attribute value for BuyerId, using the alias name BuyerId.
     * @return the BuyerId
     */
    public Number getBuyerId() {
        return (Number)getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuyerId.
     * @param value value to set the BuyerId
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for Style, using the alias name Style.
     * @return the Style
     */
    public String getStyle() {
        return (String)getAttributeInternal(STYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Style.
     * @param value value to set the Style
     */
    public void setStyle(String value) {
        setAttributeInternal(STYLE, value);
    }

    /**
     * Gets the attribute value for BpoNo, using the alias name BpoNo.
     * @return the BpoNo
     */
    public String getBpoNo() {
        return (String)getAttributeInternal(BPONO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BpoNo.
     * @param value value to set the BpoNo
     */
    public void setBpoNo(String value) {
        setAttributeInternal(BPONO, value);
    }

    /**
     * Gets the attribute value for Color, using the alias name Color.
     * @return the Color
     */
    public String getColor() {
        return (String)getAttributeInternal(COLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Color.
     * @param value value to set the Color
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**
     * Gets the attribute value for MinEndBit, using the alias name MinEndBit.
     * @return the MinEndBit
     */
    public Number getMinEndBit() {
        return (Number)getAttributeInternal(MINENDBIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for MinEndBit.
     * @param value value to set the MinEndBit
     */
    public void setMinEndBit(Number value) {
        setAttributeInternal(MINENDBIT, value);
    }

    /**
     * Gets the attribute value for MinBndSize, using the alias name MinBndSize.
     * @return the MinBndSize
     */
    public Number getMinBndSize() {
        return (Number)getAttributeInternal(MINBNDSIZE);
    }

    /**
     * Sets <code>value</code> as the attribute value for MinBndSize.
     * @param value value to set the MinBndSize
     */
    public void setMinBndSize(Number value) {
        setAttributeInternal(MINBNDSIZE, value);
    }

    /**
     * Gets the attribute value for MaxBndSize, using the alias name MaxBndSize.
     * @return the MaxBndSize
     */
    public Number getMaxBndSize() {
        return (Number)getAttributeInternal(MAXBNDSIZE);
    }

    /**
     * Sets <code>value</code> as the attribute value for MaxBndSize.
     * @param value value to set the MaxBndSize
     */
    public void setMaxBndSize(Number value) {
        setAttributeInternal(MAXBNDSIZE, value);
    }

    /**
     * Gets the attribute value for Season, using the alias name Season.
     * @return the Season
     */
    public String getSeason() {
        return (String)getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for Season.
     * @param value value to set the Season
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for Deviation, using the alias name Deviation.
     * @return the Deviation
     */
    public Number getDeviation() {
        return (Number)getAttributeInternal(DEVIATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Deviation.
     * @param value value to set the Deviation
     */
    public void setDeviation(Number value) {
        setAttributeInternal(DEVIATION, value);
    }

    /**
     * Gets the attribute value for DeviatonPrcnt, using the alias name DeviatonPrcnt.
     * @return the DeviatonPrcnt
     */
    public Number getDeviatonPrcnt() {
        return (Number)getAttributeInternal(DEVIATONPRCNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeviatonPrcnt.
     * @param value value to set the DeviatonPrcnt
     */
    public void setDeviatonPrcnt(Number value) {
        setAttributeInternal(DEVIATONPRCNT, value);
    }

    /**
     * Gets the attribute value for OrderQty, using the alias name OrderQty.
     * @return the OrderQty
     */
    public Number getOrderQty() {
        return (Number)getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderQty.
     * @param value value to set the OrderQty
     */
    public void setOrderQty(Number value) {
        setAttributeInternal(ORDERQTY, value);
    }

    /**
     * Gets the attribute value for CutQty, using the alias name CutQty.
     * @return the CutQty
     */
    public Number getCutQty() {
        return (Number)getAttributeInternal(CUTQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutQty.
     * @param value value to set the CutQty
     */
    public void setCutQty(Number value) {
        setAttributeInternal(CUTQTY, value);
    }

    /**
     * Gets the attribute value for PlanDev, using the alias name PlanDev.
     * @return the PlanDev
     */
    public Number getPlanDev() {
        return (Number)getAttributeInternal(PLANDEV);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlanDev.
     * @param value value to set the PlanDev
     */
    public void setPlanDev(Number value) {
        setAttributeInternal(PLANDEV, value);
    }

    /**
     * Gets the attribute value for PlanDevPrcnt, using the alias name PlanDevPrcnt.
     * @return the PlanDevPrcnt
     */
    public Number getPlanDevPrcnt() {
        return (Number)getAttributeInternal(PLANDEVPRCNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlanDevPrcnt.
     * @param value value to set the PlanDevPrcnt
     */
    public void setPlanDevPrcnt(Number value) {
        setAttributeInternal(PLANDEVPRCNT, value);
    }

    /**
     * Gets the attribute value for Unit, using the alias name Unit.
     * @return the Unit
     */
    public String getUnit() {
        return (String)getAttributeInternal(UNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Unit.
     * @param value value to set the Unit
     */
    public void setUnit(String value) {
        setAttributeInternal(UNIT, value);
    }

    /**
     * Gets the attribute value for Osp, using the alias name Osp.
     * @return the Osp
     */
    public String getOsp() {
        return (String)getAttributeInternal(OSP);
    }

    /**
     * Sets <code>value</code> as the attribute value for Osp.
     * @param value value to set the Osp
     */
    public void setOsp(String value) {
        setAttributeInternal(OSP, value);
    }

    /**
     * Gets the attribute value for OspUnit, using the alias name OspUnit.
     * @return the OspUnit
     */
    public String getOspUnit() {
        return (String)getAttributeInternal(OSPUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for OspUnit.
     * @param value value to set the OspUnit
     */
    public void setOspUnit(String value) {
        setAttributeInternal(OSPUNIT, value);
    }

    /**
     * Gets the attribute value for Printing, using the alias name Printing.
     * @return the Printing
     */
    public String getPrinting() {
        return (String)getAttributeInternal(PRINTING);
    }

    /**
     * Sets <code>value</code> as the attribute value for Printing.
     * @param value value to set the Printing
     */
    public void setPrinting(String value) {
        setAttributeInternal(PRINTING, value);
    }

    /**
     * Gets the attribute value for Embriodry, using the alias name Embriodry.
     * @return the Embriodry
     */
    public String getEmbriodry() {
        return (String)getAttributeInternal(EMBRIODRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Embriodry.
     * @param value value to set the Embriodry
     */
    public void setEmbriodry(String value) {
        setAttributeInternal(EMBRIODRY, value);
    }

    /**
     * Gets the attribute value for LastAction, using the alias name LastAction.
     * @return the LastAction
     */
    public String getLastAction() {
        return (String)getAttributeInternal(LASTACTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastAction.
     * @param value value to set the LastAction
     */
    public void setLastAction(String value) {
        setAttributeInternal(LASTACTION, value);
    }

    /**
     * Gets the attribute value for RatioPlanQty, using the alias name RatioPlanQty.
     * @return the RatioPlanQty
     */
    public Number getRatioPlanQty() {
        return (Number)getAttributeInternal(RATIOPLANQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for RatioPlanQty.
     * @param value value to set the RatioPlanQty
     */
    public void setRatioPlanQty(Number value) {
        setAttributeInternal(RATIOPLANQTY, value);
    }

    /**
     * Gets the attribute value for ColorId, using the alias name ColorId.
     * @return the ColorId
     */
    public String getColorId() {
        return (String)getAttributeInternal(COLORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ColorId.
     * @param value value to set the ColorId
     */
    public void setColorId(String value) {
        setAttributeInternal(COLORID, value);
    }

    /**
     * Gets the attribute value for BookingConsumption, using the alias name BookingConsumption.
     * @return the BookingConsumption
     */
    public Number getBookingConsumption() {
        return (Number)getAttributeInternal(BOOKINGCONSUMPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for BookingConsumption.
     * @param value value to set the BookingConsumption
     */
    public void setBookingConsumption(Number value) {
        setAttributeInternal(BOOKINGCONSUMPTION, value);
    }

    /**
     * Gets the attribute value for ProductionConsumption, using the alias name ProductionConsumption.
     * @return the ProductionConsumption
     */
    public Number getProductionConsumption() {
        return (Number)getAttributeInternal(PRODUCTIONCONSUMPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductionConsumption.
     * @param value value to set the ProductionConsumption
     */
    public void setProductionConsumption(Number value) {
        setAttributeInternal(PRODUCTIONCONSUMPTION, value);
    }

    /**
     * Gets the attribute value for FinishedGarmentsColor, using the alias name FinishedGarmentsColor.
     * @return the FinishedGarmentsColor
     */
    public String getFinishedGarmentsColor() {
        return (String)getAttributeInternal(FINISHEDGARMENTSCOLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for FinishedGarmentsColor.
     * @param value value to set the FinishedGarmentsColor
     */
    public void setFinishedGarmentsColor(String value) {
        setAttributeInternal(FINISHEDGARMENTSCOLOR, value);
    }

    /**
     * Gets the attribute value for Wash, using the alias name Wash.
     * @return the Wash
     */
    public String getWash() {
        return (String)getAttributeInternal(WASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Wash.
     * @param value value to set the Wash
     */
    public void setWash(String value) {
        setAttributeInternal(WASH, value);
    }

    /**
     * Gets the attribute value for SystemId, using the alias name SystemId.
     * @return the SystemId
     */
    public Number getSystemId() {
        return (Number)getAttributeInternal(SYSTEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SystemId.
     * @param value value to set the SystemId
     */
    public void setSystemId(Number value) {
        setAttributeInternal(SYSTEMID, value);
    }

    /**
     * Gets the attribute value for PocId, using the alias name PocId.
     * @return the PocId
     */
    public Number getPocId() {
        return (Number)getAttributeInternal(POCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PocId.
     * @param value value to set the PocId
     */
    public void setPocId(Number value) {
        setAttributeInternal(POCID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjMfgRatioplanObline() {
        return (RowIterator)getAttributeInternal(MNJMFGRATIOPLANOBLINE);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjMfgRatioplanPlyline() {
        return (RowIterator)getAttributeInternal(MNJMFGRATIOPLANPLYLINE);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjMfgRatioplanBposAll() {
        return (RowIterator)getAttributeInternal(MNJMFGRATIOPLANBPOSALL);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjMfgRatioplanStnsAll() {
        return (RowIterator)getAttributeInternal(MNJMFGRATIOPLANSTNSALL);
    }


    /**
     * @param ratioplanId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number ratioplanId) {
        return new Key(new Object[]{ratioplanId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =
            new oracle.jbo.server.SequenceImpl("MNJ_MFG_RATIOPLAN_S",
                                               getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setRatioplanId(sVal);
        System.out.println(sVal);


    }

    public String getSrNoString() {
        String srno = null;
        String stmt =
            "BEGIN :1 := mnj_mfg_doc_no_pkg.marker_ratio_plan_srno; end;";
        java.sql.CallableStatement cs =
            getDBTransaction().createCallableStatement(stmt, 1);
        try {
            cs.registerOutParameter(1, oracle.jdbc.OracleTypes.VARCHAR);
            cs.execute();
            srno = cs.getString(1);
            cs.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return srno;
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {

        Map sessionScope = ADFContext.getCurrent().getSessionScope();
        String user = (String)sessionScope.get("userId");
        String orgId = (String)sessionScope.get("orgId");
        String unitName = (String)sessionScope.get("unitName");


        if (operation == DML_INSERT) {


            try {
                setRatioplanNumber(getSrNoString());
                setDivisionId(orgId);
                setUnit(unitName);
                setCreationDate((Date)Date.getCurrentDate());
                setCreatedBy(new oracle.jbo.domain.Number(user));
            } catch (SQLException f) {
                ;
            }
        } else if (DML_UPDATE == operation) {
            try {
                setLastUpdateDate((Date)Date.getCurrentDate());
                setLastUpdatedBy(new oracle.jbo.domain.Number(user));
            } catch (SQLException f) {
                ;
            }
        }

        super.doDML(operation, e);

    }
}
