package mnj.mfg.model.entities;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 26 17:42:35 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgRatioplanSizlineImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DivisionId {
            public Object get(MnjMfgRatioplanSizlineImpl obj) {
                return obj.getDivisionId();
            }

            public void put(MnjMfgRatioplanSizlineImpl obj, Object value) {
                obj.setDivisionId((String)value);
            }
        }
        ,
        RatioplanId {
            public Object get(MnjMfgRatioplanSizlineImpl obj) {
                return obj.getRatioplanId();
            }

            public void put(MnjMfgRatioplanSizlineImpl obj, Object value) {
                obj.setRatioplanId((Number)value);
            }
        }
        ,
        RatioplanNumber {
            public Object get(MnjMfgRatioplanSizlineImpl obj) {
                return obj.getRatioplanNumber();
            }

            public void put(MnjMfgRatioplanSizlineImpl obj, Object value) {
                obj.setRatioplanNumber((Number)value);
            }
        }
        ,
        PlylineId {
            public Object get(MnjMfgRatioplanSizlineImpl obj) {
                return obj.getPlylineId();
            }

            public void put(MnjMfgRatioplanSizlineImpl obj, Object value) {
                obj.setPlylineId((Number)value);
            }
        }
        ,
        SizlineId {
            public Object get(MnjMfgRatioplanSizlineImpl obj) {
                return obj.getSizlineId();
            }

            public void put(MnjMfgRatioplanSizlineImpl obj, Object value) {
                obj.setSizlineId((Number)value);
            }
        }
        ,
        SalesorderId {
            public Object get(MnjMfgRatioplanSizlineImpl obj) {
                return obj.getSalesorderId();
            }

            public void put(MnjMfgRatioplanSizlineImpl obj, Object value) {
                obj.setSalesorderId((Number)value);
            }
        }
        ,
        SizeId {
            public Object get(MnjMfgRatioplanSizlineImpl obj) {
                return obj.getSizeId();
            }

            public void put(MnjMfgRatioplanSizlineImpl obj, Object value) {
                obj.setSizeId((String)value);
            }
        }
        ,
        Remarks {
            public Object get(MnjMfgRatioplanSizlineImpl obj) {
                return obj.getRemarks();
            }

            public void put(MnjMfgRatioplanSizlineImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        CuttingRatio {
            public Object get(MnjMfgRatioplanSizlineImpl obj) {
                return obj.getCuttingRatio();
            }

            public void put(MnjMfgRatioplanSizlineImpl obj, Object value) {
                obj.setCuttingRatio((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjMfgRatioplanSizlineImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjMfgRatioplanSizlineImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjMfgRatioplanSizlineImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjMfgRatioplanSizlineImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjMfgRatioplanSizlineImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjMfgRatioplanSizlineImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjMfgRatioplanSizlineImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjMfgRatioplanSizlineImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        Pcs {
            public Object get(MnjMfgRatioplanSizlineImpl obj) {
                return obj.getPcs();
            }

            public void put(MnjMfgRatioplanSizlineImpl obj, Object value) {
                obj.setPcs((Number)value);
            }
        }
        ,
        Inseam {
            public Object get(MnjMfgRatioplanSizlineImpl obj) {
                return obj.getInseam();
            }

            public void put(MnjMfgRatioplanSizlineImpl obj, Object value) {
                obj.setInseam((Number)value);
            }
        }
        ,
        SizeQty {
            public Object get(MnjMfgRatioplanSizlineImpl obj) {
                return obj.getSizeQty();
            }

            public void put(MnjMfgRatioplanSizlineImpl obj, Object value) {
                obj.setSizeQty((Number)value);
            }
        }
        ,
        PlanCutQty {
            public Object get(MnjMfgRatioplanSizlineImpl obj) {
                return obj.getPlanCutQty();
            }

            public void put(MnjMfgRatioplanSizlineImpl obj, Object value) {
                obj.setPlanCutQty((Number)value);
            }
        }
        ,
        BalQty {
            public Object get(MnjMfgRatioplanSizlineImpl obj) {
                return obj.getBalQty();
            }

            public void put(MnjMfgRatioplanSizlineImpl obj, Object value) {
                obj.setBalQty((Number)value);
            }
        }
        ,
        PlanQty {
            public Object get(MnjMfgRatioplanSizlineImpl obj) {
                return obj.getPlanQty();
            }

            public void put(MnjMfgRatioplanSizlineImpl obj, Object value) {
                obj.setPlanQty((Number)value);
            }
        }
        ,
        MnjMfgRatioplanPlyline {
            public Object get(MnjMfgRatioplanSizlineImpl obj) {
                return obj.getMnjMfgRatioplanPlyline();
            }

            public void put(MnjMfgRatioplanSizlineImpl obj, Object value) {
                obj.setMnjMfgRatioplanPlyline((MnjMfgRatioplanPlylineImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjMfgRatioplanSizlineImpl object);

        public abstract void put(MnjMfgRatioplanSizlineImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int RATIOPLANID = AttributesEnum.RatioplanId.index();
    public static final int RATIOPLANNUMBER = AttributesEnum.RatioplanNumber.index();
    public static final int PLYLINEID = AttributesEnum.PlylineId.index();
    public static final int SIZLINEID = AttributesEnum.SizlineId.index();
    public static final int SALESORDERID = AttributesEnum.SalesorderId.index();
    public static final int SIZEID = AttributesEnum.SizeId.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int CUTTINGRATIO = AttributesEnum.CuttingRatio.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int PCS = AttributesEnum.Pcs.index();
    public static final int INSEAM = AttributesEnum.Inseam.index();
    public static final int SIZEQTY = AttributesEnum.SizeQty.index();
    public static final int PLANCUTQTY = AttributesEnum.PlanCutQty.index();
    public static final int BALQTY = AttributesEnum.BalQty.index();
    public static final int PLANQTY = AttributesEnum.PlanQty.index();
    public static final int MNJMFGRATIOPLANPLYLINE = AttributesEnum.MnjMfgRatioplanPlyline.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgRatioplanSizlineImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.MnjMfgRatioplanSizline");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for DivisionId, using the alias name DivisionId.
     * @return the DivisionId
     */
    public String getDivisionId() {
        return (String)getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DivisionId.
     * @param value value to set the DivisionId
     */
    public void setDivisionId(String value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for RatioplanId, using the alias name RatioplanId.
     * @return the RatioplanId
     */
    public Number getRatioplanId() {
        return (Number)getAttributeInternal(RATIOPLANID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RatioplanId.
     * @param value value to set the RatioplanId
     */
    public void setRatioplanId(Number value) {
        setAttributeInternal(RATIOPLANID, value);
    }

    /**
     * Gets the attribute value for RatioplanNumber, using the alias name RatioplanNumber.
     * @return the RatioplanNumber
     */
    public Number getRatioplanNumber() {
        return (Number)getAttributeInternal(RATIOPLANNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for RatioplanNumber.
     * @param value value to set the RatioplanNumber
     */
    public void setRatioplanNumber(Number value) {
        setAttributeInternal(RATIOPLANNUMBER, value);
    }

    /**
     * Gets the attribute value for PlylineId, using the alias name PlylineId.
     * @return the PlylineId
     */
    public Number getPlylineId() {
        return (Number)getAttributeInternal(PLYLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlylineId.
     * @param value value to set the PlylineId
     */
    public void setPlylineId(Number value) {
        setAttributeInternal(PLYLINEID, value);
    }

    /**
     * Gets the attribute value for SizlineId, using the alias name SizlineId.
     * @return the SizlineId
     */
    public Number getSizlineId() {
        return (Number)getAttributeInternal(SIZLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizlineId.
     * @param value value to set the SizlineId
     */
    public void setSizlineId(Number value) {
        setAttributeInternal(SIZLINEID, value);
    }

    /**
     * Gets the attribute value for SalesorderId, using the alias name SalesorderId.
     * @return the SalesorderId
     */
    public Number getSalesorderId() {
        return (Number)getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesorderId.
     * @param value value to set the SalesorderId
     */
    public void setSalesorderId(Number value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for SizeId, using the alias name SizeId.
     * @return the SizeId
     */
    public String getSizeId() {
        return (String)getAttributeInternal(SIZEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeId.
     * @param value value to set the SizeId
     */
    public void setSizeId(String value) {
        setAttributeInternal(SIZEID, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for CuttingRatio, using the alias name CuttingRatio.
     * @return the CuttingRatio
     */
    public Number getCuttingRatio() {
        return (Number)getAttributeInternal(CUTTINGRATIO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CuttingRatio.
     * @param value value to set the CuttingRatio
     */
    public void setCuttingRatio(Number value) {
        setAttributeInternal(CUTTINGRATIO, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Pcs, using the alias name Pcs.
     * @return the Pcs
     */
    public Number getPcs() {
        return (Number)getAttributeInternal(PCS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Pcs.
     * @param value value to set the Pcs
     */
    public void setPcs(Number value) {
        setAttributeInternal(PCS, value);
    }

    /**
     * Gets the attribute value for Inseam, using the alias name Inseam.
     * @return the Inseam
     */
    public Number getInseam() {
        return (Number)getAttributeInternal(INSEAM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Inseam.
     * @param value value to set the Inseam
     */
    public void setInseam(Number value) {
        setAttributeInternal(INSEAM, value);
    }

    /**
     * Gets the attribute value for SizeQty, using the alias name SizeQty.
     * @return the SizeQty
     */
    public Number getSizeQty() {
        return (Number)getAttributeInternal(SIZEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeQty.
     * @param value value to set the SizeQty
     */
    public void setSizeQty(Number value) {
        setAttributeInternal(SIZEQTY, value);
    }

    /**
     * Gets the attribute value for PlanCutQty, using the alias name PlanCutQty.
     * @return the PlanCutQty
     */
    public Number getPlanCutQty() {
        return (Number)getAttributeInternal(PLANCUTQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlanCutQty.
     * @param value value to set the PlanCutQty
     */
    public void setPlanCutQty(Number value) {
        setAttributeInternal(PLANCUTQTY, value);
    }

    /**
     * Gets the attribute value for BalQty, using the alias name BalQty.
     * @return the BalQty
     */
    public Number getBalQty() {
        return (Number)getAttributeInternal(BALQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for BalQty.
     * @param value value to set the BalQty
     */
    public void setBalQty(Number value) {
        setAttributeInternal(BALQTY, value);
    }

    /**
     * Gets the attribute value for PlanQty, using the alias name PlanQty.
     * @return the PlanQty
     */
    public Number getPlanQty() {
        return (Number)getAttributeInternal(PLANQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlanQty.
     * @param value value to set the PlanQty
     */
    public void setPlanQty(Number value) {
        setAttributeInternal(PLANQTY, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity MnjMfgRatioplanPlylineImpl.
     */
    public MnjMfgRatioplanPlylineImpl getMnjMfgRatioplanPlyline() {
        return (MnjMfgRatioplanPlylineImpl)getAttributeInternal(MNJMFGRATIOPLANPLYLINE);
    }

    /**
     * Sets <code>value</code> as the associated entity MnjMfgRatioplanPlylineImpl.
     */
    public void setMnjMfgRatioplanPlyline(MnjMfgRatioplanPlylineImpl value) {
        setAttributeInternal(MNJMFGRATIOPLANPLYLINE, value);
    }


    /**
     * @param ratioplanId key constituent
     * @param plylineId key constituent
     * @param sizlineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number ratioplanId, Number plylineId,
                                       Number sizlineId) {
        return new Key(new Object[]{ratioplanId, plylineId, sizlineId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MNJ_MFG_RATIOPLAN_SIZLINE_S",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setSizlineId(sVal);
        
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Map sessionScope = ADFContext.getCurrent().getSessionScope();   
                String user = (String)sessionScope.get("userId");
                String orgId  =(String)sessionScope.get("orgId");
                String unitName  =(String)sessionScope.get("unitName");
                
                System.out.println("ASSES INS DO DML 1 ------------------>"+user);
                System.out.println("ASSES INS DO DML 2------------------>"+orgId);
                System.out.println("ASSES INS DML 3 ------------------>"+unitName);
                
                if(DML_UPDATE == operation){
                          try {
                              
                              setLastUpdateDate((Date)Date.getCurrentDate()); 
                              setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                          } catch (SQLException f) {
                              System.out.println(f.getMessage());
                          }
                      }
                      else if (DML_INSERT == operation){
                       
                          try {
                              
                              //setHeaderNo(getSrNoString());
                              //setOrgId(new oracle.jbo.domain.Number(orgId));
                              //setAttribute1(unitName);
                              setCreationDate((Date)Date.getCurrentDate());  
                              setCreatedBy(new oracle.jbo.domain.Number(user));
                             
                             
                             
                          } catch (SQLException f) {
                              ;
                          }
                      } 
        super.doDML(operation, e);
    }
}
