package mnj.mfg.model.entities;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 11 12:42:29 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgRatioplanStnsAllImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DetailId {
            public Object get(MnjMfgRatioplanStnsAllImpl obj) {
                return obj.getDetailId();
            }

            public void put(MnjMfgRatioplanStnsAllImpl obj, Object value) {
                obj.setDetailId((Number)value);
            }
        }
        ,
        LineId {
            public Object get(MnjMfgRatioplanStnsAllImpl obj) {
                return obj.getLineId();
            }

            public void put(MnjMfgRatioplanStnsAllImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        BpoNo {
            public Object get(MnjMfgRatioplanStnsAllImpl obj) {
                return obj.getBpoNo();
            }

            public void put(MnjMfgRatioplanStnsAllImpl obj, Object value) {
                obj.setBpoNo((String)value);
            }
        }
        ,
        StnNo {
            public Object get(MnjMfgRatioplanStnsAllImpl obj) {
                return obj.getStnNo();
            }

            public void put(MnjMfgRatioplanStnsAllImpl obj, Object value) {
                obj.setStnNo((String)value);
            }
        }
        ,
        InventoryItemId {
            public Object get(MnjMfgRatioplanStnsAllImpl obj) {
                return obj.getInventoryItemId();
            }

            public void put(MnjMfgRatioplanStnsAllImpl obj, Object value) {
                obj.setInventoryItemId((Number)value);
            }
        }
        ,
        ItemCode {
            public Object get(MnjMfgRatioplanStnsAllImpl obj) {
                return obj.getItemCode();
            }

            public void put(MnjMfgRatioplanStnsAllImpl obj, Object value) {
                obj.setItemCode((String)value);
            }
        }
        ,
        ItemDescription {
            public Object get(MnjMfgRatioplanStnsAllImpl obj) {
                return obj.getItemDescription();
            }

            public void put(MnjMfgRatioplanStnsAllImpl obj, Object value) {
                obj.setItemDescription((String)value);
            }
        }
        ,
        OrgId {
            public Object get(MnjMfgRatioplanStnsAllImpl obj) {
                return obj.getOrgId();
            }

            public void put(MnjMfgRatioplanStnsAllImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        StnQty {
            public Object get(MnjMfgRatioplanStnsAllImpl obj) {
                return obj.getStnQty();
            }

            public void put(MnjMfgRatioplanStnsAllImpl obj, Object value) {
                obj.setStnQty((Number)value);
            }
        }
        ,
        ItemCreated {
            public Object get(MnjMfgRatioplanStnsAllImpl obj) {
                return obj.getItemCreated();
            }

            public void put(MnjMfgRatioplanStnsAllImpl obj, Object value) {
                obj.setItemCreated((String)value);
            }
        }
        ,
        JobStatus {
            public Object get(MnjMfgRatioplanStnsAllImpl obj) {
                return obj.getJobStatus();
            }

            public void put(MnjMfgRatioplanStnsAllImpl obj, Object value) {
                obj.setJobStatus((String)value);
            }
        }
        ,
        BomCreated {
            public Object get(MnjMfgRatioplanStnsAllImpl obj) {
                return obj.getBomCreated();
            }

            public void put(MnjMfgRatioplanStnsAllImpl obj, Object value) {
                obj.setBomCreated((String)value);
            }
        }
        ,
        JobCreated {
            public Object get(MnjMfgRatioplanStnsAllImpl obj) {
                return obj.getJobCreated();
            }

            public void put(MnjMfgRatioplanStnsAllImpl obj, Object value) {
                obj.setJobCreated((String)value);
            }
        }
        ,
        RatioplanId {
            public Object get(MnjMfgRatioplanStnsAllImpl obj) {
                return obj.getRatioplanId();
            }

            public void put(MnjMfgRatioplanStnsAllImpl obj, Object value) {
                obj.setRatioplanId((Number)value);
            }
        }
        ,
        StnSequence {
            public Object get(MnjMfgRatioplanStnsAllImpl obj) {
                return obj.getStnSequence();
            }

            public void put(MnjMfgRatioplanStnsAllImpl obj, Object value) {
                obj.setStnSequence((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjMfgRatioplanStnsAllImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjMfgRatioplanStnsAllImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjMfgRatioplanStnsAllImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjMfgRatioplanStnsAllImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjMfgRatioplanStnsAllImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjMfgRatioplanStnsAllImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjMfgRatioplanStnsAllImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjMfgRatioplanStnsAllImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        BpoId {
            public Object get(MnjMfgRatioplanStnsAllImpl obj) {
                return obj.getBpoId();
            }

            public void put(MnjMfgRatioplanStnsAllImpl obj, Object value) {
                obj.setBpoId((Number)value);
            }
        }
        ,
        MnjMfgRatioplan {
            public Object get(MnjMfgRatioplanStnsAllImpl obj) {
                return obj.getMnjMfgRatioplan();
            }

            public void put(MnjMfgRatioplanStnsAllImpl obj, Object value) {
                obj.setMnjMfgRatioplan((MnjMfgRatioplanImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjMfgRatioplanStnsAllImpl object);

        public abstract void put(MnjMfgRatioplanStnsAllImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


//    public static final int MNJMFGRATIOPLANBPOSALL = AttributesEnum.MnjMfgRatioplanBposAll.index();


    public static final int DETAILID = AttributesEnum.DetailId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int BPONO = AttributesEnum.BpoNo.index();
    public static final int STNNO = AttributesEnum.StnNo.index();
    public static final int INVENTORYITEMID = AttributesEnum.InventoryItemId.index();
    public static final int ITEMCODE = AttributesEnum.ItemCode.index();
    public static final int ITEMDESCRIPTION = AttributesEnum.ItemDescription.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int STNQTY = AttributesEnum.StnQty.index();
    public static final int ITEMCREATED = AttributesEnum.ItemCreated.index();
    public static final int JOBSTATUS = AttributesEnum.JobStatus.index();
    public static final int BOMCREATED = AttributesEnum.BomCreated.index();
    public static final int JOBCREATED = AttributesEnum.JobCreated.index();
    public static final int RATIOPLANID = AttributesEnum.RatioplanId.index();
    public static final int STNSEQUENCE = AttributesEnum.StnSequence.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int BPOID = AttributesEnum.BpoId.index();
    public static final int MNJMFGRATIOPLAN = AttributesEnum.MnjMfgRatioplan.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgRatioplanStnsAllImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.MnjMfgRatioplanStnsAll");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for DetailId, using the alias name DetailId.
     * @return the DetailId
     */
    public Number getDetailId() {
        return (Number)getAttributeInternal(DETAILID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DetailId.
     * @param value value to set the DetailId
     */
    public void setDetailId(Number value) {
        setAttributeInternal(DETAILID, value);
    }

    /**
     * Gets the attribute value for LineId, using the alias name LineId.
     * @return the LineId
     */
    public Number getLineId() {
        return (Number)getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineId.
     * @param value value to set the LineId
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for BpoNo, using the alias name BpoNo.
     * @return the BpoNo
     */
    public String getBpoNo() {
        return (String)getAttributeInternal(BPONO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BpoNo.
     * @param value value to set the BpoNo
     */
    public void setBpoNo(String value) {
        setAttributeInternal(BPONO, value);
    }

    /**
     * Gets the attribute value for StnNo, using the alias name StnNo.
     * @return the StnNo
     */
    public String getStnNo() {
        return (String)getAttributeInternal(STNNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for StnNo.
     * @param value value to set the StnNo
     */
    public void setStnNo(String value) {
        setAttributeInternal(STNNO, value);
    }

    /**
     * Gets the attribute value for InventoryItemId, using the alias name InventoryItemId.
     * @return the InventoryItemId
     */
    public Number getInventoryItemId() {
        return (Number)getAttributeInternal(INVENTORYITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InventoryItemId.
     * @param value value to set the InventoryItemId
     */
    public void setInventoryItemId(Number value) {
        setAttributeInternal(INVENTORYITEMID, value);
    }

    /**
     * Gets the attribute value for ItemCode, using the alias name ItemCode.
     * @return the ItemCode
     */
    public String getItemCode() {
        return (String)getAttributeInternal(ITEMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemCode.
     * @param value value to set the ItemCode
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**
     * Gets the attribute value for ItemDescription, using the alias name ItemDescription.
     * @return the ItemDescription
     */
    public String getItemDescription() {
        return (String)getAttributeInternal(ITEMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemDescription.
     * @param value value to set the ItemDescription
     */
    public void setItemDescription(String value) {
        setAttributeInternal(ITEMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for StnQty, using the alias name StnQty.
     * @return the StnQty
     */
    public Number getStnQty() {
        return (Number)getAttributeInternal(STNQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for StnQty.
     * @param value value to set the StnQty
     */
    public void setStnQty(Number value) {
        setAttributeInternal(STNQTY, value);
    }

    /**
     * Gets the attribute value for ItemCreated, using the alias name ItemCreated.
     * @return the ItemCreated
     */
    public String getItemCreated() {
        return (String)getAttributeInternal(ITEMCREATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemCreated.
     * @param value value to set the ItemCreated
     */
    public void setItemCreated(String value) {
        setAttributeInternal(ITEMCREATED, value);
    }

    /**
     * Gets the attribute value for JobStatus, using the alias name JobStatus.
     * @return the JobStatus
     */
    public String getJobStatus() {
        return (String)getAttributeInternal(JOBSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobStatus.
     * @param value value to set the JobStatus
     */
    public void setJobStatus(String value) {
        setAttributeInternal(JOBSTATUS, value);
    }

    /**
     * Gets the attribute value for BomCreated, using the alias name BomCreated.
     * @return the BomCreated
     */
    public String getBomCreated() {
        return (String)getAttributeInternal(BOMCREATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for BomCreated.
     * @param value value to set the BomCreated
     */
    public void setBomCreated(String value) {
        setAttributeInternal(BOMCREATED, value);
    }

    /**
     * Gets the attribute value for JobCreated, using the alias name JobCreated.
     * @return the JobCreated
     */
    public String getJobCreated() {
        return (String)getAttributeInternal(JOBCREATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobCreated.
     * @param value value to set the JobCreated
     */
    public void setJobCreated(String value) {
        setAttributeInternal(JOBCREATED, value);
    }

    /**
     * Gets the attribute value for RatioplanId, using the alias name RatioplanId.
     * @return the RatioplanId
     */
    public Number getRatioplanId() {
        return (Number)getAttributeInternal(RATIOPLANID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RatioplanId.
     * @param value value to set the RatioplanId
     */
    public void setRatioplanId(Number value) {
        setAttributeInternal(RATIOPLANID, value);
    }

    /**
     * Gets the attribute value for StnSequence, using the alias name StnSequence.
     * @return the StnSequence
     */
    public Number getStnSequence() {
        return (Number)getAttributeInternal(STNSEQUENCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StnSequence.
     * @param value value to set the StnSequence
     */
    public void setStnSequence(Number value) {
        setAttributeInternal(STNSEQUENCE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for BpoId, using the alias name BpoId.
     * @return the BpoId
     */
    public Number getBpoId() {
        return (Number)getAttributeInternal(BPOID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BpoId.
     * @param value value to set the BpoId
     */
    public void setBpoId(Number value) {
        setAttributeInternal(BPOID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity MnjMfgRatioplanImpl.
     */
    public MnjMfgRatioplanImpl getMnjMfgRatioplan() {
        return (MnjMfgRatioplanImpl)getAttributeInternal(MNJMFGRATIOPLAN);
    }

    /**
     * Sets <code>value</code> as the associated entity MnjMfgRatioplanImpl.
     */
    public void setMnjMfgRatioplan(MnjMfgRatioplanImpl value) {
        setAttributeInternal(MNJMFGRATIOPLAN, value);
    }


    /**
     * @return the associated entity MnjMfgRatioplanBposAllImpl.
     */
//    public MnjMfgRatioplanBposAllImpl getMnjMfgRatioplanBposAll() {
//        return (MnjMfgRatioplanBposAllImpl)getAttributeInternal(MNJMFGRATIOPLANBPOSALL);
//    }

    /**
     * Sets <code>value</code> as the associated entity MnjMfgRatioplanBposAllImpl.
     */
//    public void setMnjMfgRatioplanBposAll(MnjMfgRatioplanBposAllImpl value) {
//        setAttributeInternal(MNJMFGRATIOPLANBPOSALL, value);
//    }


    /**
     * @param detailId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number detailId) {
        return new Key(new Object[]{detailId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MNJ_MFG_RATIOPLAN_STNS_ALL_s",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setDetailId(sVal);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Map sessionScope = ADFContext.getCurrent().getSessionScope();   
                String user = (String)sessionScope.get("userId");
                String orgId  =(String)sessionScope.get("orgId");
                String unitName  =(String)sessionScope.get("unitName");
                
                System.out.println("ASSES INS DO DML 1 ------------------>"+user);
                System.out.println("ASSES INS DO DML 2------------------>"+orgId);
                System.out.println("ASSES INS DML 3 ------------------>"+unitName);
                
                if(DML_UPDATE == operation){
                          try {
                              
                              setLastUpdateDate((Date)Date.getCurrentDate()); 
                              setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                          } catch (SQLException f) {
                              System.out.println(f.getMessage());
                          }
                      }
                      else if (DML_INSERT == operation){
                       
                          try {
                              
                              //setHeaderNo(getSrNoString());
                              //setOrgId(new oracle.jbo.domain.Number(orgId));
                              //setAttribute1(unitName);
                              setCreationDate((Date)Date.getCurrentDate());  
                              setCreatedBy(new oracle.jbo.domain.Number(user));
                             
                             
                             
                          } catch (SQLException f) {
                              ;
                          }
                      } 
                
        super.doDML(operation, e);
    }
}
