package mnj.mfg.model.entities;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 26 17:38:27 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgRatioplanPlycflineImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DivisionId {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getDivisionId();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setDivisionId((String)value);
            }
        }
        ,
        RatioplanId {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getRatioplanId();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setRatioplanId((Number)value);
            }
        }
        ,
        RatioplanNumber {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getRatioplanNumber();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setRatioplanNumber((Number)value);
            }
        }
        ,
        PlylineId {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getPlylineId();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setPlylineId((Number)value);
            }
        }
        ,
        PlycflineId {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getPlycflineId();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setPlycflineId((Number)value);
            }
        }
        ,
        Fabricwidth {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getFabricwidth();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setFabricwidth((String)value);
            }
        }
        ,
        FabricPattern {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getFabricPattern();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setFabricPattern((String)value);
            }
        }
        ,
        Markerlength {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getMarkerlength();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setMarkerlength((Number)value);
            }
        }
        ,
        Cf {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getCf();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setCf((Number)value);
            }
        }
        ,
        ExtraMtr {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getExtraMtr();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setExtraMtr((Number)value);
            }
        }
        ,
        CuttingRatio {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getCuttingRatio();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setCuttingRatio((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        Shrinkage {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getShrinkage();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setShrinkage((Number)value);
            }
        }
        ,
        CutNo {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getCutNo();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setCutNo((String)value);
            }
        }
        ,
        NoOfPly {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getNoOfPly();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setNoOfPly((Number)value);
            }
        }
        ,
        TotalPcs {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getTotalPcs();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setTotalPcs((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getRemarks();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        SrCutNo {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getSrCutNo();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setSrCutNo((Number)value);
            }
        }
        ,
        BlncPly {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getBlncPly();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setBlncPly((Number)value);
            }
        }
        ,
        BlncPcs {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getBlncPcs();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setBlncPcs((Number)value);
            }
        }
        ,
        ProductionType {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getProductionType();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setProductionType((String)value);
            }
        }
        ,
        MnjMfgRatioplanPlyline {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getMnjMfgRatioplanPlyline();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setMnjMfgRatioplanPlyline((MnjMfgRatioplanPlylineImpl)value);
            }
        }
        ,
        MarkerLayplanDet {
            public Object get(MnjMfgRatioplanPlycflineImpl obj) {
                return obj.getMarkerLayplanDet();
            }

            public void put(MnjMfgRatioplanPlycflineImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjMfgRatioplanPlycflineImpl object);

        public abstract void put(MnjMfgRatioplanPlycflineImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int RATIOPLANID = AttributesEnum.RatioplanId.index();
    public static final int RATIOPLANNUMBER = AttributesEnum.RatioplanNumber.index();
    public static final int PLYLINEID = AttributesEnum.PlylineId.index();
    public static final int PLYCFLINEID = AttributesEnum.PlycflineId.index();
    public static final int FABRICWIDTH = AttributesEnum.Fabricwidth.index();
    public static final int FABRICPATTERN = AttributesEnum.FabricPattern.index();
    public static final int MARKERLENGTH = AttributesEnum.Markerlength.index();
    public static final int CF = AttributesEnum.Cf.index();
    public static final int EXTRAMTR = AttributesEnum.ExtraMtr.index();
    public static final int CUTTINGRATIO = AttributesEnum.CuttingRatio.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int SHRINKAGE = AttributesEnum.Shrinkage.index();
    public static final int CUTNO = AttributesEnum.CutNo.index();
    public static final int NOOFPLY = AttributesEnum.NoOfPly.index();
    public static final int TOTALPCS = AttributesEnum.TotalPcs.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int SRCUTNO = AttributesEnum.SrCutNo.index();
    public static final int BLNCPLY = AttributesEnum.BlncPly.index();
    public static final int BLNCPCS = AttributesEnum.BlncPcs.index();
    public static final int PRODUCTIONTYPE = AttributesEnum.ProductionType.index();
    public static final int MNJMFGRATIOPLANPLYLINE = AttributesEnum.MnjMfgRatioplanPlyline.index();
    public static final int MARKERLAYPLANDET = AttributesEnum.MarkerLayplanDet.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgRatioplanPlycflineImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.MnjMfgRatioplanPlycfline");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for DivisionId, using the alias name DivisionId.
     * @return the DivisionId
     */
    public String getDivisionId() {
        return (String)getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DivisionId.
     * @param value value to set the DivisionId
     */
    public void setDivisionId(String value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for RatioplanId, using the alias name RatioplanId.
     * @return the RatioplanId
     */
    public Number getRatioplanId() {
        return (Number)getAttributeInternal(RATIOPLANID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RatioplanId.
     * @param value value to set the RatioplanId
     */
    public void setRatioplanId(Number value) {
        setAttributeInternal(RATIOPLANID, value);
    }

    /**
     * Gets the attribute value for RatioplanNumber, using the alias name RatioplanNumber.
     * @return the RatioplanNumber
     */
    public Number getRatioplanNumber() {
        return (Number)getAttributeInternal(RATIOPLANNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for RatioplanNumber.
     * @param value value to set the RatioplanNumber
     */
    public void setRatioplanNumber(Number value) {
        setAttributeInternal(RATIOPLANNUMBER, value);
    }

    /**
     * Gets the attribute value for PlylineId, using the alias name PlylineId.
     * @return the PlylineId
     */
    public Number getPlylineId() {
        return (Number)getAttributeInternal(PLYLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlylineId.
     * @param value value to set the PlylineId
     */
    public void setPlylineId(Number value) {
        setAttributeInternal(PLYLINEID, value);
    }

    /**
     * Gets the attribute value for PlycflineId, using the alias name PlycflineId.
     * @return the PlycflineId
     */
    public Number getPlycflineId() {
        return (Number)getAttributeInternal(PLYCFLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlycflineId.
     * @param value value to set the PlycflineId
     */
    public void setPlycflineId(Number value) {
        setAttributeInternal(PLYCFLINEID, value);
    }

    /**
     * Gets the attribute value for Fabricwidth, using the alias name Fabricwidth.
     * @return the Fabricwidth
     */
    public String getFabricwidth() {
        return (String)getAttributeInternal(FABRICWIDTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Fabricwidth.
     * @param value value to set the Fabricwidth
     */
    public void setFabricwidth(String value) {
        setAttributeInternal(FABRICWIDTH, value);
    }

    /**
     * Gets the attribute value for FabricPattern, using the alias name FabricPattern.
     * @return the FabricPattern
     */
    public String getFabricPattern() {
        return (String)getAttributeInternal(FABRICPATTERN);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabricPattern.
     * @param value value to set the FabricPattern
     */
    public void setFabricPattern(String value) {
        setAttributeInternal(FABRICPATTERN, value);
    }

    /**
     * Gets the attribute value for Markerlength, using the alias name Markerlength.
     * @return the Markerlength
     */
    public Number getMarkerlength() {
        return (Number)getAttributeInternal(MARKERLENGTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Markerlength.
     * @param value value to set the Markerlength
     */
    public void setMarkerlength(Number value) {
        setAttributeInternal(MARKERLENGTH, value);
    }

    /**
     * Gets the attribute value for Cf, using the alias name Cf.
     * @return the Cf
     */
    public Number getCf() {
        return (Number)getAttributeInternal(CF);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cf.
     * @param value value to set the Cf
     */
    public void setCf(Number value) {
        setAttributeInternal(CF, value);
    }

    /**
     * Gets the attribute value for ExtraMtr, using the alias name ExtraMtr.
     * @return the ExtraMtr
     */
    public Number getExtraMtr() {
        return (Number)getAttributeInternal(EXTRAMTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtraMtr.
     * @param value value to set the ExtraMtr
     */
    public void setExtraMtr(Number value) {
        setAttributeInternal(EXTRAMTR, value);
    }

    /**
     * Gets the attribute value for CuttingRatio, using the alias name CuttingRatio.
     * @return the CuttingRatio
     */
    public Number getCuttingRatio() {
        return (Number)getAttributeInternal(CUTTINGRATIO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CuttingRatio.
     * @param value value to set the CuttingRatio
     */
    public void setCuttingRatio(Number value) {
        setAttributeInternal(CUTTINGRATIO, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Shrinkage, using the alias name Shrinkage.
     * @return the Shrinkage
     */
    public Number getShrinkage() {
        return (Number)getAttributeInternal(SHRINKAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Shrinkage.
     * @param value value to set the Shrinkage
     */
    public void setShrinkage(Number value) {
        setAttributeInternal(SHRINKAGE, value);
    }

    /**
     * Gets the attribute value for CutNo, using the alias name CutNo.
     * @return the CutNo
     */
    public String getCutNo() {
        return (String)getAttributeInternal(CUTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutNo.
     * @param value value to set the CutNo
     */
    public void setCutNo(String value) {
        setAttributeInternal(CUTNO, value);
    }

    /**
     * Gets the attribute value for NoOfPly, using the alias name NoOfPly.
     * @return the NoOfPly
     */
    public Number getNoOfPly() {
        return (Number)getAttributeInternal(NOOFPLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for NoOfPly.
     * @param value value to set the NoOfPly
     */
    public void setNoOfPly(Number value) {
        setAttributeInternal(NOOFPLY, value);
    }

    /**
     * Gets the attribute value for TotalPcs, using the alias name TotalPcs.
     * @return the TotalPcs
     */
    public Number getTotalPcs() {
        return (Number)getAttributeInternal(TOTALPCS);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalPcs.
     * @param value value to set the TotalPcs
     */
    public void setTotalPcs(Number value) {
        setAttributeInternal(TOTALPCS, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for SrCutNo, using the alias name SrCutNo.
     * @return the SrCutNo
     */
    public Number getSrCutNo() {
        return (Number)getAttributeInternal(SRCUTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SrCutNo.
     * @param value value to set the SrCutNo
     */
    public void setSrCutNo(Number value) {
        setAttributeInternal(SRCUTNO, value);
    }

    /**
     * Gets the attribute value for BlncPly, using the alias name BlncPly.
     * @return the BlncPly
     */
    public Number getBlncPly() {
        return (Number)getAttributeInternal(BLNCPLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for BlncPly.
     * @param value value to set the BlncPly
     */
    public void setBlncPly(Number value) {
        setAttributeInternal(BLNCPLY, value);
    }

    /**
     * Gets the attribute value for BlncPcs, using the alias name BlncPcs.
     * @return the BlncPcs
     */
    public Number getBlncPcs() {
        return (Number)getAttributeInternal(BLNCPCS);
    }

    /**
     * Sets <code>value</code> as the attribute value for BlncPcs.
     * @param value value to set the BlncPcs
     */
    public void setBlncPcs(Number value) {
        setAttributeInternal(BLNCPCS, value);
    }

    /**
     * Gets the attribute value for ProductionType, using the alias name ProductionType.
     * @return the ProductionType
     */
    public String getProductionType() {
        return (String)getAttributeInternal(PRODUCTIONTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductionType.
     * @param value value to set the ProductionType
     */
    public void setProductionType(String value) {
        setAttributeInternal(PRODUCTIONTYPE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public MnjMfgRatioplanPlylineImpl getMnjMfgRatioplanPlyline() {
        return (MnjMfgRatioplanPlylineImpl)getAttributeInternal(MNJMFGRATIOPLANPLYLINE);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setMnjMfgRatioplanPlyline(MnjMfgRatioplanPlylineImpl value) {
        setAttributeInternal(MNJMFGRATIOPLANPLYLINE, value);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMarkerLayplanDet() {
        return (RowIterator)getAttributeInternal(MARKERLAYPLANDET);
    }


    /**
     * @param ratioplanId key constituent
     * @param plylineId key constituent
     * @param plycflineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number ratioplanId, Number plylineId,
                                       Number plycflineId) {
        return new Key(new Object[]{ratioplanId, plylineId, plycflineId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MNJ_MFG_RATIOPLAN_PLYCFLINE_S",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setPlycflineId(sVal);
        
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Map sessionScope = ADFContext.getCurrent().getSessionScope();   
                String user = (String)sessionScope.get("userId");
                String orgId  =(String)sessionScope.get("orgId");
                String unitName  =(String)sessionScope.get("unitName");
                
                System.out.println("ASSES INS DO DML 1 ------------------>"+user);
                System.out.println("ASSES INS DO DML 2------------------>"+orgId);
                System.out.println("ASSES INS DML 3 ------------------>"+unitName);
                
                if(DML_UPDATE == operation){
                          try {
                              
                              setLastUpdateDate((Date)Date.getCurrentDate()); 
                              setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                          } catch (SQLException f) {
                              System.out.println(f.getMessage());
                          }
                      }
                      else if (DML_INSERT == operation){
                       
                          try {
                              
                              //setHeaderNo(getSrNoString());
                              //setOrgId(new oracle.jbo.domain.Number(orgId));
                              //setAttribute1(unitName);
                              setCreationDate((Date)Date.getCurrentDate());  
                              setCreatedBy(new oracle.jbo.domain.Number(user));
                             
                             
                             
                          } catch (SQLException f) {
                              ;
                          }
                      } 
                
        super.doDML(operation, e);
    }
}
