package mnj.mfg.model.entities;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 25 16:26:37 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgMarkerBundleDetImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    @Override
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =
            new oracle.jbo.server.SequenceImpl("MNJ_MFG_MARKER_BUNDLE_DET_S",
                                               getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setDetailId(sVal);
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DetailId {
            public Object get(MnjMfgMarkerBundleDetImpl obj) {
                return obj.getDetailId();
            }

            public void put(MnjMfgMarkerBundleDetImpl obj, Object value) {
                obj.setDetailId((Number)value);
            }
        }
        ,
        SizlineId {
            public Object get(MnjMfgMarkerBundleDetImpl obj) {
                return obj.getSizlineId();
            }

            public void put(MnjMfgMarkerBundleDetImpl obj, Object value) {
                obj.setSizlineId((Number)value);
            }
        }
        ,
        RatioplanId {
            public Object get(MnjMfgMarkerBundleDetImpl obj) {
                return obj.getRatioplanId();
            }

            public void put(MnjMfgMarkerBundleDetImpl obj, Object value) {
                obj.setRatioplanId((Number)value);
            }
        }
        ,
        PlylineId {
            public Object get(MnjMfgMarkerBundleDetImpl obj) {
                return obj.getPlylineId();
            }

            public void put(MnjMfgMarkerBundleDetImpl obj, Object value) {
                obj.setPlylineId((Number)value);
            }
        }
        ,
        Style {
            public Object get(MnjMfgMarkerBundleDetImpl obj) {
                return obj.getStyle();
            }

            public void put(MnjMfgMarkerBundleDetImpl obj, Object value) {
                obj.setStyle((String)value);
            }
        }
        ,
        SizeValue {
            public Object get(MnjMfgMarkerBundleDetImpl obj) {
                return obj.getSizeValue();
            }

            public void put(MnjMfgMarkerBundleDetImpl obj, Object value) {
                obj.setSizeValue((String)value);
            }
        }
        ,
        BundleNo {
            public Object get(MnjMfgMarkerBundleDetImpl obj) {
                return obj.getBundleNo();
            }

            public void put(MnjMfgMarkerBundleDetImpl obj, Object value) {
                obj.setBundleNo((Number)value);
            }
        }
        ,
        FromPieceNo {
            public Object get(MnjMfgMarkerBundleDetImpl obj) {
                return obj.getFromPieceNo();
            }

            public void put(MnjMfgMarkerBundleDetImpl obj, Object value) {
                obj.setFromPieceNo((Number)value);
            }
        }
        ,
        ToPieceNo {
            public Object get(MnjMfgMarkerBundleDetImpl obj) {
                return obj.getToPieceNo();
            }

            public void put(MnjMfgMarkerBundleDetImpl obj, Object value) {
                obj.setToPieceNo((Number)value);
            }
        }
        ,
        Shade {
            public Object get(MnjMfgMarkerBundleDetImpl obj) {
                return obj.getShade();
            }

            public void put(MnjMfgMarkerBundleDetImpl obj, Object value) {
                obj.setShade((String)value);
            }
        }
        ,
        SeqNo {
            public Object get(MnjMfgMarkerBundleDetImpl obj) {
                return obj.getSeqNo();
            }

            public void put(MnjMfgMarkerBundleDetImpl obj, Object value) {
                obj.setSeqNo((Number)value);
            }
        }
        ,
        PlycflineId {
            public Object get(MnjMfgMarkerBundleDetImpl obj) {
                return obj.getPlycflineId();
            }

            public void put(MnjMfgMarkerBundleDetImpl obj, Object value) {
                obj.setPlycflineId((Number)value);
            }
        }
        ,
        Parts {
            public Object get(MnjMfgMarkerBundleDetImpl obj) {
                return obj.getParts();
            }

            public void put(MnjMfgMarkerBundleDetImpl obj, Object value) {
                obj.setParts((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjMfgMarkerBundleDetImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjMfgMarkerBundleDetImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjMfgMarkerBundleDetImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjMfgMarkerBundleDetImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjMfgMarkerBundleDetImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjMfgMarkerBundleDetImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjMfgMarkerBundleDetImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjMfgMarkerBundleDetImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        MnjMfgRatioplanPlyline {
            public Object get(MnjMfgMarkerBundleDetImpl obj) {
                return obj.getMnjMfgRatioplanPlyline();
            }

            public void put(MnjMfgMarkerBundleDetImpl obj, Object value) {
                obj.setMnjMfgRatioplanPlyline((MnjMfgRatioplanPlylineImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjMfgMarkerBundleDetImpl object);

        public abstract void put(MnjMfgMarkerBundleDetImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


//    public static final int MNJMFGRATIOPLANPLYLINE = AttributesEnum.MnjMfgRatioplanPlyline.index();


    public static final int DETAILID = AttributesEnum.DetailId.index();
    public static final int SIZLINEID = AttributesEnum.SizlineId.index();
    public static final int RATIOPLANID = AttributesEnum.RatioplanId.index();
    public static final int PLYLINEID = AttributesEnum.PlylineId.index();
    public static final int STYLE = AttributesEnum.Style.index();
    public static final int SIZEVALUE = AttributesEnum.SizeValue.index();
    public static final int BUNDLENO = AttributesEnum.BundleNo.index();
    public static final int FROMPIECENO = AttributesEnum.FromPieceNo.index();
    public static final int TOPIECENO = AttributesEnum.ToPieceNo.index();
    public static final int SHADE = AttributesEnum.Shade.index();
    public static final int SEQNO = AttributesEnum.SeqNo.index();
    public static final int PLYCFLINEID = AttributesEnum.PlycflineId.index();
    public static final int PARTS = AttributesEnum.Parts.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int MNJMFGRATIOPLANPLYLINE = AttributesEnum.MnjMfgRatioplanPlyline.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgMarkerBundleDetImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.MnjMfgMarkerBundleDet");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for DetailId, using the alias name DetailId.
     * @return the DetailId
     */
    public Number getDetailId() {
        return (Number)getAttributeInternal(DETAILID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DetailId.
     * @param value value to set the DetailId
     */
    public void setDetailId(Number value) {
        setAttributeInternal(DETAILID, value);
    }

    /**
     * Gets the attribute value for SizlineId, using the alias name SizlineId.
     * @return the SizlineId
     */
    public Number getSizlineId() {
        return (Number)getAttributeInternal(SIZLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizlineId.
     * @param value value to set the SizlineId
     */
    public void setSizlineId(Number value) {
        setAttributeInternal(SIZLINEID, value);
    }

    /**
     * Gets the attribute value for RatioplanId, using the alias name RatioplanId.
     * @return the RatioplanId
     */
    public Number getRatioplanId() {
        return (Number)getAttributeInternal(RATIOPLANID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RatioplanId.
     * @param value value to set the RatioplanId
     */
    public void setRatioplanId(Number value) {
        setAttributeInternal(RATIOPLANID, value);
    }

    /**
     * Gets the attribute value for PlylineId, using the alias name PlylineId.
     * @return the PlylineId
     */
    public Number getPlylineId() {
        return (Number)getAttributeInternal(PLYLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlylineId.
     * @param value value to set the PlylineId
     */
    public void setPlylineId(Number value) {
        setAttributeInternal(PLYLINEID, value);
    }

    /**
     * Gets the attribute value for Style, using the alias name Style.
     * @return the Style
     */
    public String getStyle() {
        return (String)getAttributeInternal(STYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Style.
     * @param value value to set the Style
     */
    public void setStyle(String value) {
        setAttributeInternal(STYLE, value);
    }

    /**
     * Gets the attribute value for SizeValue, using the alias name SizeValue.
     * @return the SizeValue
     */
    public String getSizeValue() {
        return (String)getAttributeInternal(SIZEVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeValue.
     * @param value value to set the SizeValue
     */
    public void setSizeValue(String value) {
        setAttributeInternal(SIZEVALUE, value);
    }

    /**
     * Gets the attribute value for BundleNo, using the alias name BundleNo.
     * @return the BundleNo
     */
    public Number getBundleNo() {
        return (Number)getAttributeInternal(BUNDLENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BundleNo.
     * @param value value to set the BundleNo
     */
    public void setBundleNo(Number value) {
        setAttributeInternal(BUNDLENO, value);
    }

    /**
     * Gets the attribute value for FromPieceNo, using the alias name FromPieceNo.
     * @return the FromPieceNo
     */
    public Number getFromPieceNo() {
        return (Number)getAttributeInternal(FROMPIECENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for FromPieceNo.
     * @param value value to set the FromPieceNo
     */
    public void setFromPieceNo(Number value) {
        setAttributeInternal(FROMPIECENO, value);
    }

    /**
     * Gets the attribute value for ToPieceNo, using the alias name ToPieceNo.
     * @return the ToPieceNo
     */
    public Number getToPieceNo() {
        return (Number)getAttributeInternal(TOPIECENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ToPieceNo.
     * @param value value to set the ToPieceNo
     */
    public void setToPieceNo(Number value) {
        setAttributeInternal(TOPIECENO, value);
    }

    /**
     * Gets the attribute value for Shade, using the alias name Shade.
     * @return the Shade
     */
    public String getShade() {
        return (String)getAttributeInternal(SHADE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Shade.
     * @param value value to set the Shade
     */
    public void setShade(String value) {
        setAttributeInternal(SHADE, value);
    }

    /**
     * Gets the attribute value for SeqNo, using the alias name SeqNo.
     * @return the SeqNo
     */
    public Number getSeqNo() {
        return (Number)getAttributeInternal(SEQNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SeqNo.
     * @param value value to set the SeqNo
     */
    public void setSeqNo(Number value) {
        setAttributeInternal(SEQNO, value);
    }

    /**
     * Gets the attribute value for PlycflineId, using the alias name PlycflineId.
     * @return the PlycflineId
     */
    public Number getPlycflineId() {
        return (Number)getAttributeInternal(PLYCFLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlycflineId.
     * @param value value to set the PlycflineId
     */
    public void setPlycflineId(Number value) {
        setAttributeInternal(PLYCFLINEID, value);
    }

    /**
     * Gets the attribute value for Parts, using the alias name Parts.
     * @return the Parts
     */
    public String getParts() {
        return (String)getAttributeInternal(PARTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Parts.
     * @param value value to set the Parts
     */
    public void setParts(String value) {
        setAttributeInternal(PARTS, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity MnjMfgRatioplanPlylineImpl.
     */
//    public MnjMfgRatioplanPlylineImpl getMnjMfgRatioplanPlyline() {
//        return (MnjMfgRatioplanPlylineImpl)getAttributeInternal(MNJMFGRATIOPLANPLYLINE);
//    }

    /**
     * Sets <code>value</code> as the associated entity MnjMfgRatioplanPlylineImpl.
     */
//    public void setMnjMfgRatioplanPlyline(MnjMfgRatioplanPlylineImpl value) {
//        setAttributeInternal(MNJMFGRATIOPLANPLYLINE, value);
//    }


    /**
     * @return the associated entity MnjMfgRatioplanPlylineImpl.
     */
    public MnjMfgRatioplanPlylineImpl getMnjMfgRatioplanPlyline() {
        return (MnjMfgRatioplanPlylineImpl)getAttributeInternal(MNJMFGRATIOPLANPLYLINE);
    }

    /**
     * Sets <code>value</code> as the associated entity MnjMfgRatioplanPlylineImpl.
     */
    public void setMnjMfgRatioplanPlyline(MnjMfgRatioplanPlylineImpl value) {
        setAttributeInternal(MNJMFGRATIOPLANPLYLINE, value);
    }

    /**
     * @param detailId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number detailId) {
        return new Key(new Object[]{detailId});
    }
    
    /**
         * Custom DML update/insert/delete logic here.
         * @param operation the operation type
         * @param e the transaction event
         */
        protected void doDML(int operation, TransactionEvent e) {
            Map sessionScope = ADFContext.getCurrent().getSessionScope();   
            String user = (String)sessionScope.get("userId");
            String orgId  =(String)sessionScope.get("orgId");
            String unitName  =(String)sessionScope.get("unitName");
            
            System.out.println("ASSES INS DO DML 1 ------------------>"+user);
            System.out.println("ASSES INS DO DML 2------------------>"+orgId);
            System.out.println("ASSES INS DML 3 ------------------>"+unitName);
            
            if(DML_UPDATE == operation){
                      try {
                          
                          setLastUpdateDate((Date)Date.getCurrentDate()); 
                          setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                      } catch (SQLException f) {
                          System.out.println(f.getMessage());
                      }
                  }
                  else if (DML_INSERT == operation){
                   
                      try {
                          
                          //setHeaderNo(getSrNoString());
                          //setOrgId(new oracle.jbo.domain.Number(orgId));
                          //setAttribute1(unitName);
                          setCreationDate((Date)Date.getCurrentDate());  
                          setCreatedBy(new oracle.jbo.domain.Number(user));
                         
                         
                         
                      } catch (SQLException f) {
                          ;
                      }
                  } 
            
            super.doDML(operation, e);
        }


}
