package mnj.mfg.model.entities;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 26 17:33:26 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgRatioplanOblineImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DivisionId {
            public Object get(MnjMfgRatioplanOblineImpl obj) {
                return obj.getDivisionId();
            }

            public void put(MnjMfgRatioplanOblineImpl obj, Object value) {
                obj.setDivisionId((String)value);
            }
        }
        ,
        RatioplanId {
            public Object get(MnjMfgRatioplanOblineImpl obj) {
                return obj.getRatioplanId();
            }

            public void put(MnjMfgRatioplanOblineImpl obj, Object value) {
                obj.setRatioplanId((Number)value);
            }
        }
        ,
        RatioplanNumber {
            public Object get(MnjMfgRatioplanOblineImpl obj) {
                return obj.getRatioplanNumber();
            }

            public void put(MnjMfgRatioplanOblineImpl obj, Object value) {
                obj.setRatioplanNumber((Number)value);
            }
        }
        ,
        OblineId {
            public Object get(MnjMfgRatioplanOblineImpl obj) {
                return obj.getOblineId();
            }

            public void put(MnjMfgRatioplanOblineImpl obj, Object value) {
                obj.setOblineId((Number)value);
            }
        }
        ,
        SalesorderId {
            public Object get(MnjMfgRatioplanOblineImpl obj) {
                return obj.getSalesorderId();
            }

            public void put(MnjMfgRatioplanOblineImpl obj, Object value) {
                obj.setSalesorderId((Number)value);
            }
        }
        ,
        SolineId {
            public Object get(MnjMfgRatioplanOblineImpl obj) {
                return obj.getSolineId();
            }

            public void put(MnjMfgRatioplanOblineImpl obj, Object value) {
                obj.setSolineId((Number)value);
            }
        }
        ,
        InseamId {
            public Object get(MnjMfgRatioplanOblineImpl obj) {
                return obj.getInseamId();
            }

            public void put(MnjMfgRatioplanOblineImpl obj, Object value) {
                obj.setInseamId((String)value);
            }
        }
        ,
        Quantity {
            public Object get(MnjMfgRatioplanOblineImpl obj) {
                return obj.getQuantity();
            }

            public void put(MnjMfgRatioplanOblineImpl obj, Object value) {
                obj.setQuantity((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjMfgRatioplanOblineImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjMfgRatioplanOblineImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjMfgRatioplanOblineImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjMfgRatioplanOblineImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjMfgRatioplanOblineImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjMfgRatioplanOblineImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjMfgRatioplanOblineImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjMfgRatioplanOblineImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        JobId {
            public Object get(MnjMfgRatioplanOblineImpl obj) {
                return obj.getJobId();
            }

            public void put(MnjMfgRatioplanOblineImpl obj, Object value) {
                obj.setJobId((Number)value);
            }
        }
        ,
        JobStatus {
            public Object get(MnjMfgRatioplanOblineImpl obj) {
                return obj.getJobStatus();
            }

            public void put(MnjMfgRatioplanOblineImpl obj, Object value) {
                obj.setJobStatus((String)value);
            }
        }
        ,
        PostedStatus {
            public Object get(MnjMfgRatioplanOblineImpl obj) {
                return obj.getPostedStatus();
            }

            public void put(MnjMfgRatioplanOblineImpl obj, Object value) {
                obj.setPostedStatus((String)value);
            }
        }
        ,
        SolineNumber {
            public Object get(MnjMfgRatioplanOblineImpl obj) {
                return obj.getSolineNumber();
            }

            public void put(MnjMfgRatioplanOblineImpl obj, Object value) {
                obj.setSolineNumber((Number)value);
            }
        }
        ,
        WipJobId {
            public Object get(MnjMfgRatioplanOblineImpl obj) {
                return obj.getWipJobId();
            }

            public void put(MnjMfgRatioplanOblineImpl obj, Object value) {
                obj.setWipJobId((Number)value);
            }
        }
        ,
        FlagEnabled {
            public Object get(MnjMfgRatioplanOblineImpl obj) {
                return obj.getFlagEnabled();
            }

            public void put(MnjMfgRatioplanOblineImpl obj, Object value) {
                obj.setFlagEnabled((String)value);
            }
        }
        ,
        MnjMfgRatioplan {
            public Object get(MnjMfgRatioplanOblineImpl obj) {
                return obj.getMnjMfgRatioplan();
            }

            public void put(MnjMfgRatioplanOblineImpl obj, Object value) {
                obj.setMnjMfgRatioplan((MnjMfgRatioplanImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjMfgRatioplanOblineImpl object);

        public abstract void put(MnjMfgRatioplanOblineImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int RATIOPLANID = AttributesEnum.RatioplanId.index();
    public static final int RATIOPLANNUMBER = AttributesEnum.RatioplanNumber.index();
    public static final int OBLINEID = AttributesEnum.OblineId.index();
    public static final int SALESORDERID = AttributesEnum.SalesorderId.index();
    public static final int SOLINEID = AttributesEnum.SolineId.index();
    public static final int INSEAMID = AttributesEnum.InseamId.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int JOBID = AttributesEnum.JobId.index();
    public static final int JOBSTATUS = AttributesEnum.JobStatus.index();
    public static final int POSTEDSTATUS = AttributesEnum.PostedStatus.index();
    public static final int SOLINENUMBER = AttributesEnum.SolineNumber.index();
    public static final int WIPJOBID = AttributesEnum.WipJobId.index();
    public static final int FLAGENABLED = AttributesEnum.FlagEnabled.index();
    public static final int MNJMFGRATIOPLAN = AttributesEnum.MnjMfgRatioplan.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgRatioplanOblineImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.MnjMfgRatioplanObline");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for DivisionId, using the alias name DivisionId.
     * @return the DivisionId
     */
    public String getDivisionId() {
        return (String)getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DivisionId.
     * @param value value to set the DivisionId
     */
    public void setDivisionId(String value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for RatioplanId, using the alias name RatioplanId.
     * @return the RatioplanId
     */
    public Number getRatioplanId() {
        return (Number)getAttributeInternal(RATIOPLANID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RatioplanId.
     * @param value value to set the RatioplanId
     */
    public void setRatioplanId(Number value) {
        setAttributeInternal(RATIOPLANID, value);
    }

    /**
     * Gets the attribute value for RatioplanNumber, using the alias name RatioplanNumber.
     * @return the RatioplanNumber
     */
    public Number getRatioplanNumber() {
        return (Number)getAttributeInternal(RATIOPLANNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for RatioplanNumber.
     * @param value value to set the RatioplanNumber
     */
    public void setRatioplanNumber(Number value) {
        setAttributeInternal(RATIOPLANNUMBER, value);
    }

    /**
     * Gets the attribute value for OblineId, using the alias name OblineId.
     * @return the OblineId
     */
    public Number getOblineId() {
        return (Number)getAttributeInternal(OBLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OblineId.
     * @param value value to set the OblineId
     */
    public void setOblineId(Number value) {
        setAttributeInternal(OBLINEID, value);
    }

    /**
     * Gets the attribute value for SalesorderId, using the alias name SalesorderId.
     * @return the SalesorderId
     */
    public Number getSalesorderId() {
        return (Number)getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesorderId.
     * @param value value to set the SalesorderId
     */
    public void setSalesorderId(Number value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for SolineId, using the alias name SolineId.
     * @return the SolineId
     */
    public Number getSolineId() {
        return (Number)getAttributeInternal(SOLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SolineId.
     * @param value value to set the SolineId
     */
    public void setSolineId(Number value) {
        setAttributeInternal(SOLINEID, value);
    }

    /**
     * Gets the attribute value for InseamId, using the alias name InseamId.
     * @return the InseamId
     */
    public String getInseamId() {
        return (String)getAttributeInternal(INSEAMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InseamId.
     * @param value value to set the InseamId
     */
    public void setInseamId(String value) {
        setAttributeInternal(INSEAMID, value);
    }

    /**
     * Gets the attribute value for Quantity, using the alias name Quantity.
     * @return the Quantity
     */
    public Number getQuantity() {
        return (Number)getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Quantity.
     * @param value value to set the Quantity
     */
    public void setQuantity(Number value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for JobId, using the alias name JobId.
     * @return the JobId
     */
    public Number getJobId() {
        return (Number)getAttributeInternal(JOBID);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobId.
     * @param value value to set the JobId
     */
    public void setJobId(Number value) {
        setAttributeInternal(JOBID, value);
    }

    /**
     * Gets the attribute value for JobStatus, using the alias name JobStatus.
     * @return the JobStatus
     */
    public String getJobStatus() {
        return (String)getAttributeInternal(JOBSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobStatus.
     * @param value value to set the JobStatus
     */
    public void setJobStatus(String value) {
        setAttributeInternal(JOBSTATUS, value);
    }

    /**
     * Gets the attribute value for PostedStatus, using the alias name PostedStatus.
     * @return the PostedStatus
     */
    public String getPostedStatus() {
        return (String)getAttributeInternal(POSTEDSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for PostedStatus.
     * @param value value to set the PostedStatus
     */
    public void setPostedStatus(String value) {
        setAttributeInternal(POSTEDSTATUS, value);
    }

    /**
     * Gets the attribute value for SolineNumber, using the alias name SolineNumber.
     * @return the SolineNumber
     */
    public Number getSolineNumber() {
        return (Number)getAttributeInternal(SOLINENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for SolineNumber.
     * @param value value to set the SolineNumber
     */
    public void setSolineNumber(Number value) {
        setAttributeInternal(SOLINENUMBER, value);
    }

    /**
     * Gets the attribute value for WipJobId, using the alias name WipJobId.
     * @return the WipJobId
     */
    public Number getWipJobId() {
        return (Number)getAttributeInternal(WIPJOBID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WipJobId.
     * @param value value to set the WipJobId
     */
    public void setWipJobId(Number value) {
        setAttributeInternal(WIPJOBID, value);
    }

    /**
     * Gets the attribute value for FlagEnabled, using the alias name FlagEnabled.
     * @return the FlagEnabled
     */
    public String getFlagEnabled() {
        return (String)getAttributeInternal(FLAGENABLED);
    }

    /**
     * Sets <code>value</code> as the attribute value for FlagEnabled.
     * @param value value to set the FlagEnabled
     */
    public void setFlagEnabled(String value) {
        setAttributeInternal(FLAGENABLED, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity MnjMfgRatioplanImpl.
     */
    public MnjMfgRatioplanImpl getMnjMfgRatioplan() {
        return (MnjMfgRatioplanImpl)getAttributeInternal(MNJMFGRATIOPLAN);
    }

    /**
     * Sets <code>value</code> as the associated entity MnjMfgRatioplanImpl.
     */
    public void setMnjMfgRatioplan(MnjMfgRatioplanImpl value) {
        setAttributeInternal(MNJMFGRATIOPLAN, value);
    }


    /**
     * @param ratioplanId key constituent
     * @param oblineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number ratioplanId, Number oblineId) {
        return new Key(new Object[]{ratioplanId, oblineId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MNJ_MFG_RATIOPLAN_OBLINE_S",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setOblineId(sVal);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
