package mnj.mfg.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 11 18:30:28 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InseamVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public InseamVOImpl() {
        
//        this.setFullSqlMode(FULLSQL_MODE_AUGMENTATION);
//        this.setQuery("select l.inseam, d.size_value, sum(d.size_qty) qty\n" + 
//        "                          from cust_mnj_ont_so_obin_sizline l,\n" + 
//        "                         cust_mnj_ont_so_obinsline    d\n" + 
//        "                         where l.SO_OBINSLINE_ID = d.SO_OBINSLINE_ID\n" + 
//        "                           and l.soline_id in ('5027', '5029')\n" + 
//        "                         group by l.inseam, d.size_value");
//        this.executeQuery();
    }
}
