package mnj.mfg.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 15 15:58:11 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NewInseamLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public NewInseamLOVImpl() {
    }


    /**
     * Returns the bind variable value for P_RATIO_PLAN_ID.
     * @return bind variable value for P_RATIO_PLAN_ID
     */
    public String getP_RATIO_PLAN_ID() {
        return (String)getNamedWhereClauseParam("P_RATIO_PLAN_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_RATIO_PLAN_ID.
     * @param value value to bind as P_RATIO_PLAN_ID
     */
    public void setP_RATIO_PLAN_ID(String value) {
        setNamedWhereClauseParam("P_RATIO_PLAN_ID", value);
    }
}
